cognitedata/toolkit

poetry.lock
pyproject.toml
scripts/utils.py
tests/scripts/test_utils.py

A bit messy mocking, but it's a start

Unit tests for the Client initiator class

---

common/cdf_auth_readwrite_all/auth/infield.config.readonly.yaml

Added group to be able to view infield config as read-only user

---

.github/workflows/dev.yml
.vscode/launch.json
scripts/load.py

* Sequence write of views, containers, and data models
* If drop is set, write unchanged entities

Sequence write of views, containers, and data models

---

scripts/utils.py

Fix issue where we have many ACLs of the same type

Refactor how we check ACLs to cater for multiple ACLs

---

deploy.py

This is useful when developing locally and need to switch between which modules you deploy.

Interactive deploy

---

scripts/templates.py

Was a small confusion in Huntsman.

Log  build clean success

---

.github/workflows/dev.yml
cdf.py
scripts/bootstrap.py

* Simplify how to --update-group
* Add --create-group support

Update auth verify group update + create

---

cognite_toolkit/cdf_tk/load.py
cognite_toolkit/examples/cdf_apm_simple/timeseries/timeseries.yaml
tests/conftest.py
tests/test_approval_modules.py
tests/test_approval_modules_snapshots/cdf_apm_base.yaml
tests/test_approval_modules_snapshots/cdf_apm_simple.yaml
tests/test_approval_modules_snapshots/cdf_asset_source_model.yaml
tests/test_approval_modules_snapshots/cdf_infield_common.yaml
tests/test_approval_modules_snapshots/cdf_infield_location.yaml
tests/test_approval_modules_snapshots/example_pump_asset_hierarchy.yaml
tests/test_approval_modules_snapshots/example_pump_data_model.yaml

**Bonus** Found a bug in the TimeSeries configuration.

Extended approval test with drop = True

---

.github/workflows/release.yaml

Push to pypi prod

---

CHANGELOG.cdf-tk.md
CHANGELOG.templates.md
cognite_toolkit/cdf.py
cognite_toolkit/cdf_tk/load.py
cognite_toolkit/cdf_tk/utils.py
tests/test_cdf_tk/test_load.py

Changelog updates and special treatment of Groups to run first to give general access, and then the scoped access after all resources have been created. 
Tested locally with a Service Principal with only Projects and Groups capabilities. 

Changelog update + CI Fix

---

CHANGELOG.cdf-tk.md
cognite_toolkit/cdf.py
cognite_toolkit/cdf_tk/load.py
cognite_toolkit/cdf_tk/utils.py
tests/conftest.py
tests/test_cdf_tk/load_data/data_sets/1.my_datasets.yaml
tests/test_cdf_tk/test_load.py
tests/test_cdf_tk/test_utils.py

Upsert datasets

---

.pre-commit-config.yaml
cognite_toolkit/cdf.py
cognite_toolkit/cdf_tk/load.py
tests/test_approval_modules_snapshots/cdf_oid_example_data.yaml
tests/test_approval_modules_snapshots/example_pump_asset_hierarchy.yaml
tests/test_cdf_tk/test_load.py

To refactor the `load_data_models` I need an explicit way of handling dependencies, so introduced this mechanism. 
Will take the refactoring of `load_data_models` in a separate PR to keep the size small
Pure refactoring so no changelog entry. 

Cleanup Order. 

---

.github/workflows/demo.yml
CHANGELOG.cdf-tk.md
cognite_toolkit/_version.py
cognite_toolkit/cdf_tk/load.py
cognite_toolkit/cdf_tk/templates.py
cognite_toolkit/modules/cdf_infield_location/transformations/tr_asset_oid_workmate_infield_sync_assets_from_hierarchy_to_apm.yaml
cognite_toolkit/modules/cdf_infield_location/transformations/tr_workorder_oid_workmate_infield_sync_workorders_to_apm_activities.yaml
demo/postproc.py
pyproject.toml
tests/test_approval_modules_snapshots/cdf_infield_location.yaml

- Fix wrong space names in transformations
- Fix postproc wrong transformations

Fix wrong space names and transformation names

---

.github/workflows/build.yml

Additional testing that the happy path flow works as expected. 

Dry Run Job

---

.github/workflows/build.yml
.github/workflows/demo.yml
.github/workflows/release.yaml
.pre-commit-config.yaml
poetry.lock
pyproject.toml

Upgrade packages and lock file

Package upgrades

---

CHANGELOG.cdf-tk.md
cognite_toolkit/cdf.py
cognite_toolkit/cdf_tk/load.py

Fix Group Creation Bug

---

cognite_toolkit/cognite_modules/examples/cdf_data_pipeline_asset_valhall/extraction_pipelines/source_asset_valhall_workmate.config.yaml
cognite_toolkit/cognite_modules/examples/cdf_data_pipeline_asset_valhall/transformations/tr_asset_oid_workmate_asset_hierarchy.yaml

added dataSetExternalId to configuration

---

cognite_toolkit/cdf.py
cognite_toolkit/cdf_tk/utils.py
demo/postproc.py
tests/test_cdf_tk/test_utils.py

Set client name for logging

---

tr_asset_oid_workmate_apm_simple_load_assets.schedule.yaml
tr_timeseries_oid_pi_apm_simple_load_timeseries2assets.schedule.yaml
tr_workorder_oid_workmate_apm_simple_load_workitems.schedule.yaml
tr_workorder_oid_workmate_apm_simple_load_workitems2assets.schedule.yaml
tr_workorder_oid_workmate_apm_simple_load_workitems2workorders.schedule.yaml
tr_workorder_oid_workmate_apm_simple_load_workorders.schedule.yaml
tr_workorder_oid_workmate_apm_simple_load_workorders2assets.schedule.yaml

Deleted files that shouldn't have been there in  the first place

---

CONTRIBUTING.md
cdf-tk-dev.py
cognite_toolkit/cdf.py
poetry.lock
pyproject.toml

Add sentry

---

.pre-commit-config.yaml
cognite_toolkit/cdf_tk/bootstrap.py

Adding `mypy` check to the `cognite_toolkit/cdf_tk/bootstrap.py`. I have done a minimal amount of changes, and instead tried to just add type hints to reflect the actual types that are being used. 

[CDF-20588] MyPy Part 2

---

.pre-commit-config.yaml
cognite_toolkit/cdf_tk/delete.py
cognite_toolkit/cdf_tk/dump.py

[CDF-20588] MyPy Part 3 of 6

---

cognite_toolkit/cognite_modules/examples/cdf_data_pipeline_asset_valhall/transformations/tr_asset_oid_workmate_asset_hierarchy.yaml

Update with asset dataset

---

cognite_toolkit/cdf.py
cognite_toolkit/cdf_tk/load.py
cognite_toolkit/cdf_tk/templates.py
tests/test_approval_modules_snapshots/cdf_oid_example_data.yaml

This pull request includes the following changes:
- Added datapoints to the oid data set
- Fixed issues with the datapoints csv loader and improved error messages
- Fixed Windows loading of csv files
- Added support for timeshift of timeseries data

Add datapoints to oid data set and fix issues with datapoints csv loader and Windows loading of csv and support timeshift of timeseries

---

.pre-commit-config.yaml
cognite_toolkit/cdf_tk/load.py
cognite_toolkit/cdf_tk/utils.py
tests/conftest.py

This also prepares for write classes, which is currently only used in data modeling, but will be available for all Cognite Resources once this one is merged https://github.com/cognitedata/cognite-sdk-python/pull/1567

[CDF-20588] MyPy part4

---

.github/workflows/build.yml

Merge after #267 Which have the bugfix for the 3.11 failing

ci: Test on 3.11

---

CHANGELOG.cdf-tk.md
cognite_toolkit/cdf_tk/templates.py
cognite_toolkit/cdf_tk/utils.py
tests/approval_client.py
tests/conftest.py
tests/test_approval_modules.py
tests/test_approval_modules_snapshots/cdf_apm_simple_data_model.yaml
tests/test_approval_modules_snapshots/cdf_asset_source_model.yaml
tests/test_approval_modules_snapshots/cdf_data_pipeline_asset_valhall.yaml
tests/test_approval_modules_snapshots/cdf_infield_location.yaml
tests/test_approval_modules_snapshots/cdf_oid_example_data.yaml
tests/test_approval_modules_snapshots/example_pump_asset_hierarchy.yaml
tests/test_approval_modules_snapshots/example_pump_data_model.yaml
tests/test_behavior.py
tests/test_cdf_tk/test_load.py
tests/test_cdf_tk/test_run.py
tests/utils.py

[CDF-20650] - Support injecting custom environmental variables

---

CHANGELOG.cdf-tk.md
cognite_toolkit/cdf.py

fix: dotenv not relative to cwd

---

tests/test_integration/constants.py
tests/test_integration/test_loaders/test_resource_container_loaders.py

[POWEROPS-20763] Fix race conditions

---

cognite_toolkit/cdf_tk/templates.py

Extends the error message for missing variables in `cdf-tk build` if they are found at another level
Instead of
```
WARNING: Unresolved template variable {{cdfProjectName}} in build\timeseries\1.timeseries.yaml
```
we also get
```
WARNING: Unresolved template variable {{cdfProjectName}} in build\timeseries\1.timeseries.yaml
Hint: The variables in 'config.yaml' are defined in a tree structure, i.e., variables defined at a higher level can be used in lower levels.
The variable 'cdfProjectName' is defined in the following module: 'cognite_modules'
needs to be moved up in the config structure to be used in 'custom_modules.my_example_module'.
``` …

[CDF-20802] docs; improved error message

---

.github/workflows/release.yaml

Missing env variables

---

.gitignore
cdf-tk-dev.py

Create config.local.yaml on-the-fly

---

cognite_toolkit/cdf_tk/templates/data_classes/_project_directory.py

fix: hotfix common modules

---

cognite_toolkit/cdf_tk/templates/data_classes/_project_directory.py

fix: hotfix common modules (#322)

---

cognite_toolkit/cdf_tk/templates/data_classes/_project_directory.py

Release 0.1.0b7

---

cognite_toolkit/cdf_tk/templates/__init__.py
cognite_toolkit/cdf_tk/templates/_utils.py
tests/tests_unit/test_cdf_tk/test_templates.py

refactor: helper module_from_path

---

CHANGELOG.cdf-tk.md
cognite_toolkit/cdf_tk/describe.py
cognite_toolkit/cdf_tk/load/_resource_loaders.py
tests/tests_unit/approval_client.py
tests/tests_unit/test_cdf_tk/test_load.py

[CDF-20922] View children always detected changed.

---

CHANGELOG.cdf-tk.md
cognite_toolkit/cdf_tk/load/_resource_loaders.py
tests/tests_unit/test_cdf_tk/test_load.py

CDF-20683 support for group list in a single file

---

cognite_toolkit/cdf_tk/run.py
tests/tests_unit/test_cdf_tk/run_data/cognite_modules/_system.yaml
tests/tests_unit/test_cdf_tk/test_run.py

[CDF-20961] Add back test

---

.github/workflows/build.yml
cognite_toolkit/cdf_tk/templates/_templates.py
poetry.lock
pyproject.toml

Allow 3.12

---

CHANGELOG.cdf-tk.md

build; changelog entry

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/utils.py
tests/tests_unit/test_approval_modules_snapshots/cdf_data_pipeline_files_valhall.yaml
tests/tests_unit/test_approval_modules_snapshots/cdf_functions_dummy.yaml
tests/tests_unit/test_cdf_tk/test_utils.py

Fix hashing dir

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/load/_resource_loaders.py

fix: respect HasData filter limit

---

.github/workflows/build.yml

ci: fix trigger test on release branch as well

---

CHANGELOG.templates.md
cognite_toolkit/cognite_modules/examples/cdf_data_pipeline_files_valhall/functions/fn_context_files_oid_fileshare_annotation/pipeline.py
tests/tests_unit/test_approval_modules_snapshots/cdf_data_pipeline_files_valhall.yaml

Fixing P&ID annotation based on learnings from AkerBP project

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/load/_base_loaders.py
cognite_toolkit/_cdf_tk/load/_resource_loaders.py
tests/tests_unit/conftest.py
tests/tests_unit/test_cdf_tk/test_load.py

Scoped capabilites based on resource to load.

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/utils.py
tests/tests_unit/test_cdf_tk/test_utils.py

Index error initializing from token

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py
tests/tests_unit/conftest.py
tests/tests_unit/test_behavior.py
tests/tests_unit/test_cdf_tk/constants.py
tests/tests_unit/test_cdf_tk/project_no_cognite_modules/config.dev.yaml
tests/tests_unit/test_cdf_tk/project_no_cognite_modules/custom_modules/a_module/data_sets/datasets.yaml
tests/tests_unit/test_cdf_tk/project_no_cognite_modules/custom_modules/a_module/timeseries/timeseries.yaml
tests/tests_unit/test_cdf_tk/project_no_cognite_modules/custom_modules/another_module/data_models/a_space.space.yaml

[CDF-21186] Remove system yaml Requirement

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/utils.py
tests/tests_unit/test_cdf_tk/test_utils.py
tests/tests_unit/utils.py

[CDF-21191] Warning on missing environment variables

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/templates/__init__.py
cognite_toolkit/_cdf_tk/templates/_constants.py
tests/tests_unit/test_behavior.py

revert: CLI standalone

---

cognite_toolkit/_cdf.py

[CDF-21261] Help Breaking typer installation

---

CHANGELOG.templates.md
cognite_toolkit/cognite_modules/examples/cdf_oid_example_data/default.config.yaml
cognite_toolkit/cognite_modules/examples/cdf_oid_example_data/transformations/tr_event_oid_workmate_workitem_example.schedule.yaml
cognite_toolkit/cognite_modules/examples/cdf_oid_example_data/transformations/tr_event_oid_workmate_workitem_example.sql
cognite_toolkit/cognite_modules/examples/cdf_oid_example_data/transformations/tr_event_oid_workmate_workitem_example.yaml
cognite_toolkit/cognite_modules/examples/cdf_oid_example_data/transformations/tr_event_oid_workmate_workorder_example.schedule.yaml
cognite_toolkit/cognite_modules/examples/cdf_oid_example_data/transformations/tr_event_oid_workmate_workorder_example.sql
cognite_toolkit/cognite_modules/examples/cdf_oid_example_data/transformations/tr_event_oid_workmate_workorder_example.yaml
demo/config.demo.yaml
tests/tests_unit/test_approval_modules_snapshots/cdf_oid_example_data.yaml
tests/tests_unit/test_approval_modules_snapshots_clean/cdf_oid_example_data.yaml
tests/tests_unit/test_cdf_tk/auth_data_snapshots/auth_auth_verify_happypath_windows.txt
tests/tests_unit/test_cdf_tk/auth_data_snapshots/auth_auth_verify_no_capabilities_windows.txt
tests/tests_unit/test_cdf_tk/auth_data_snapshots/auth_auth_verify_two_groups_windows.txt
tests/tests_unit/test_cdf_tk/auth_data_snapshots/auth_auth_verify_wrong_capabilities_windows.txt

added transformations for workorder & workitems to oid test data module

---

CHANGELOG.cdf-tk.md
cognite_toolkit/.gitignore
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/templates/_templates.py
tests/tests_unit/test_approval_modules.py
tests/tests_unit/test_behavior.py
tests/tests_unit/test_cdf_tk/test_build_files.py

Ignore build folder and default to clean

---

cognite_toolkit/_cdf.py

set release in `sentry_sdk.init`

---

cognite_toolkit/custom_modules/my_example_module/timeseries/timeseries.yaml

metadata is dict, not list

---

tests/tests_unit/approval_client/client.py
tests/tests_unit/test_approval_modules_snapshots/cdf_data_pipeline_timeseries_valhall.yaml
tests/tests_unit/test_approval_modules_snapshots/cdf_oid_example_data.yaml
tests/tests_unit/test_approval_modules_snapshots/example_pump_asset_hierarchy.yaml
tests/tests_unit/test_cdf_tk/load_data_snapshots/timeseries_datapoints.yaml

Remove hashing and replacing it with aggregates about the dataframe as well as first and last row. The goal is to have easier inspection of what has changed from run to run with the small risk that there are changes we might not capture with the aggregates and first and last row

[CDF-21166] Remove hashing of dataframe

---

tests/tests_integration/test_loaders/test_resource_container_loaders.py

[CDF-21415] Attempt at fixing flaky test

---

cdf-tk-dev.py
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/utils.py

Makes it a bit more pretty, and more verbose:

add error type to output msg

---

cognite_toolkit/_cdf_tk/pull.py

[CDF-21340] Consistent writing cdf-tk pull

---

cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/utils.py

improved error handling, click/typer should not reach sentry

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/load/_resource_loaders.py
tests/tests_integration/test_loaders/test_resource_loaders.py

[CDF-21453] Update Function Schedule Bug.

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/templates/_utils.py
cognite_toolkit/_cdf_tk/templates/data_classes/_project_directory.py

[CDF-21445] Fix init --upgrade

---

CHANGELOG.templates.md
cognite_toolkit/cognite_modules/experimental/example_pump_data_model/data_models/4.Pump.view.yaml
poetry.lock
pyproject.toml
tests/tests_unit/test_approval_modules_snapshots/cdf_apm_simple_data_model.yaml
tests/tests_unit/test_approval_modules_snapshots/cdf_asset_source_model.yaml
tests/tests_unit/test_approval_modules_snapshots/cdf_infield_location.yaml
tests/tests_unit/test_approval_modules_snapshots/cdf_infield_second_location.yaml
tests/tests_unit/test_approval_modules_snapshots/example_pump_data_model.yaml

In the robustification of the loading methods in the `7.38.3` there two impacts on this package. See comments below.

[prep for CDF-21281]To python sdk 7.39

---

cognite_toolkit/_cdf_tk/load/_base_loaders.py
cognite_toolkit/_cdf_tk/load/_resource_loaders.py

[CDF-21456] No more magic

---

cognite_toolkit/_cdf_tk/utils.py

We read a lot of `YAML` and just remembered that I found this one in an earlier project which gives a good speedup.

Need4more speed

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/templates/_utils.py

[CDF-21484] Search system yaml 🐛

---

cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/_commands.py
cognite_toolkit/_cdf_tk/clean.py

[CDF-21284] 🏋Base cls commands

---

cognite_toolkit/_cdf_tk/templates/_templates.py
tests/tests_unit/test_cdf_tk/test_templates.py

Refactor `check_yaml_semantics` function

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/load/_resource_loaders.py

[CDF-21525] 🔨Load containers fix

---

cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/tk_warnings/base.py
cognite_toolkit/_cdf_tk/tk_warnings/other.py

Using Warning class instead of inline warning

---

poetry.lock
pyproject.toml

This fixes https://cognitedata.atlassian.net/browse/CDF-21155
as well as includes a bugfix in SDK that can lead deleting/creating data modeling resources to hit an API error for more than 100 items.

build; update cognite-sdk to 7.43.5

---

cognite_toolkit/_cdf_tk/load/_base_loaders.py

[CDF-21446] 👶Not case sensitive file pattern

---

cognite_toolkit/_cdf_tk/commands/_base.py
cognite_toolkit/_cdf_tk/commands/_utils.py
cognite_toolkit/_cdf_tk/commands/clean.py
cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/load/_resource_loaders.py
tests/tests_unit/test_cdf_tk/test_load.py

* `GroupLoader` to ABC
* Use composition in deploy command.

	🕵Review Feedback

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py
tests/tests_unit/test_cdf_tk/test_load.py

[CDF-21645] 👮Warning on a valid container with direct relation constraint.

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py

🐵 Remove . requirement

---

.github/workflows/release.yaml

🥷 remove requirement for release

---

cognite_toolkit/_cdf_tk/commands/auth.py
cognite_toolkit/_cdf_tk/exceptions.py
cognite_toolkit/_cdf_tk/utils.py
tests/tests_unit/test_cdf_tk/test_auth.py
tests/tests_unit/test_cdf_tk/test_utils.py

[CDF-21720] ⛲ Raise on location for auth

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/auth.py

[CDF-21433] 💬 Error message on wrong project.

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/build.py

[CDF-21719] 😵Duplicated raw DB warnings

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/build.py

[CDF-21822] 🪛Fix attribute error

---

cognite_toolkit/_cdf_tk/commands/build.py

Now we expect `fileId` not to be set to anything.

[CDF-21824] 😊Removed obsolete warning

---

cognite_toolkit/cognite_modules/README.md
cognite_toolkit/custom_modules/README.md

Replaced misleading/outdated info with links to docs

Removed misleading info

---

tests/tests_integration/test_loaders/test_resource_container_loaders.py

[CDF-21830]🤕 Added flaky decorator on flaky test

---

.vscode/launch.json
cognite_toolkit/_cdf_tk/prototypes/_packages/empty/empty_module/default.config.yaml
cognite_toolkit/_cdf_tk/prototypes/_packages/empty/manifest.yaml
cognite_toolkit/_cdf_tk/prototypes/_packages/empty/my_module/default.config.yaml
cognite_toolkit/_cdf_tk/prototypes/commands/modules.py

Fine-tuned selection logic

---

cognite_toolkit/_cdf_tk/commands/auth.py
cognite_toolkit/_cdf_tk/commands/clean.py
cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/commands/describe.py
cognite_toolkit/_cdf_tk/commands/dump.py
cognite_toolkit/_cdf_tk/constants.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py
cognite_toolkit/_cdf_tk/utils.py
tests/tests_unit/conftest.py
tests/tests_unit/test_cdf_tk/test_commands/test_auth.py
tests/tests_unit/test_cdf_tk/test_commands/test_describe.py
tests/tests_unit/test_cdf_tk/test_commands/test_run.py
tests/tests_unit/test_cdf_tk/test_loaders/test_base_loaders.py
tests/tests_unit/test_cdf_tk/test_loaders/test_data_model_loader.py
tests/tests_unit/test_cdf_tk/test_loaders/test_data_set_loader.py
tests/tests_unit/test_cdf_tk/test_loaders/test_extraction_pipeline_loader.py
tests/tests_unit/test_cdf_tk/test_loaders/test_function_loader.py
tests/tests_unit/test_cdf_tk/test_loaders/test_time_series_loader.py
tests/tests_unit/test_cdf_tk/test_loaders/test_view_loader.py
tests/tests_unit/test_cdf_tk/test_utils.py
tests/tests_unit/test_cdf_tk/tests_constants.py

[CDF-21817] 😈Check Toolkit Group Correctly setup

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/_migration.yaml

[CDF-21908] 🤦Fix manual upgrade 0.1.4

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/prototypes/commands/import_.py

[CDF-21905] 😞Bug in import transformation-cli manifest

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/build.py
tests/data/project_no_cognite_modules/config.dev.yaml
tests/data/project_no_cognite_modules/modules/a_module/data_sets/extraction.DataSet.yaml
tests/data/project_no_cognite_modules/modules/a_module/extraction_pipelines/my.ExtractionPipeline.yaml
tests/data/project_no_cognite_modules/modules/a_module/raw/all.RawTable.yaml
tests/tests_unit/test_cdf_tk/test_commands/test_build.py
tests/tests_unit/test_cli/test_behavior.py

[CDF-21904] 😕Warning missig raw table

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/build.py

[CDF-21902] 🤏Not warn about system spaces.

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py
tests/data/project_no_cognite_modules/config.dev.yaml
tests/data/project_no_cognite_modules/modules/another_module/data_models/my.Container.yaml
tests/data/project_no_cognite_modules/modules/another_module/data_models/my.View.yaml
tests/tests_unit/test_cdf_tk/test_commands/test_build.py

[CDF-21909] 🐺Warning on has data filter

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/tk_warnings/__init__.py
cognite_toolkit/_cdf_tk/tk_warnings/base.py
cognite_toolkit/_cdf_tk/tk_warnings/other.py

[CDF-21912]🦦 Moved Verbose 

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/data_classes/_config_yaml.py
poetry.lock
pyproject.toml
tests/data/describe_data/data_models/1.Asset.container.yaml
tests/data/describe_data/data_models/2.WorkOrder.container.yaml
tests/data/describe_data/data_models/3.WorkItem.container.yaml
tests/data/describe_data/data_models/4.Asset.view.yaml
tests/data/describe_data/data_models/5.WorkItem.view.yaml
tests/data/describe_data/data_models/6.WorkOrder.view.yaml
tests/tests_unit/test_cdf_tk/test_loaders/test_view_loader.py
tests/tests_unit/test_cdf_tk/test_parameters/test_functions.py
tests/tests_unit/test_cli/test_behavior.py
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_apm_base.yaml
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_apm_simple_data_model.yaml
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_asset_source_model.yaml
tests/tests_unit/test_cli/test_build_deploy_snapshots/example_pump_data_model.yaml

Upgraded `cognite-SDK` to `7.52` which introduced `immutable` as properties for views and containers. Thus the need to update test data.

[CDF-21918] 🖐Allow type test and qa

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py

[CDF-21940] 🫣 Manual inspect of load_resource methods

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/build.py
tests/tests_unit/test_cdf_tk/test_commands/test_build.py
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_apm_simple_data_model.yaml
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_asset_source_model.yaml
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_asset_valhall.yaml
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_files_valhall.yaml
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_infield_location.yaml
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_infield_second_location.yaml
tests/tests_unit/test_cli/test_build_deploy_snapshots/example_pump_asset_hierarchy.yaml
tests/tests_unit/test_cli/test_build_deploy_snapshots/example_pump_data_model.yaml

[CDF-21944] Fix sql replace

---

CHANGELOG.cdf-tk.md
CHANGELOG.templates.md
cognite_toolkit/_cdf_tk/commands/run.py
cognite_toolkit/cognite_modules/examples/cdf_functions_dummy/functions/fn_example_repeater/requirements.txt
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_functions_dummy.yaml

[CDF-21947] 🧑‍🚒Fix run function locally

---

CONTRIBUTING.md

Remembering to update instructions

amending release instructions

---

CONTRIBUTING.md
cognite_toolkit/_cdf.py
dev.py

You can now run `python dev.py --patch` to do a patch bump.

[CDF-21967, CDF-21966] 🏴‍☠️Fast bumping

---

README.md

Docs: update URLs

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/build.py
tests/data/project_no_cognite_modules/config.dev.yaml
tests/data/project_no_cognite_modules/modules/another_module/data_sets/datasets.yaml
tests/data/project_no_cognite_modules/modules/another_module/transformations/subfolder/my.Transformation.sql
tests/data/project_no_cognite_modules/modules/another_module/transformations/subfolder/my.Transformation.yaml
tests/data/project_no_cognite_modules/modules/another_module/transformations/subfolder/some.Notification.yaml
tests/tests_unit/test_cdf_tk/test_commands/test_build.py

[CDF-21976] 🐛Build overwrite bug

---

pyproject.toml

Support CDF cmd

---

cognite_toolkit/_cdf_tk/client/__init__.py
cognite_toolkit/_cdf_tk/client/api/robotics/__init__.py
cognite_toolkit/_cdf_tk/client/api/robotics/api.py
cognite_toolkit/_cdf_tk/client/api/robotics/capabilities.py
cognite_toolkit/_cdf_tk/client/api/robotics/data_postprocessing.py
cognite_toolkit/_cdf_tk/client/api/robotics/data_processing.py
cognite_toolkit/_cdf_tk/client/api/robotics/frames.py
cognite_toolkit/_cdf_tk/client/api/robotics/locations.py
cognite_toolkit/_cdf_tk/client/api/robotics/maps.py
cognite_toolkit/_cdf_tk/client/api/robotics/missions.py
cognite_toolkit/_cdf_tk/client/api/robotics/robots.py
cognite_toolkit/_cdf_tk/client/api/robotics/schedules.py
cognite_toolkit/_cdf_tk/client/api/robotics/utlis.py
cognite_toolkit/_cdf_tk/client/api/robotics/waypoints.py
cognite_toolkit/_cdf_tk/client/api_client.py
cognite_toolkit/_cdf_tk/client/data_classes/robotics.py
cognite_toolkit/_cdf_tk/utils.py
tests/tests_integration/conftest.py
tests/tests_integration/test_toolkit_client/test_robotics.py

[CDF-21960] 🤖 Preview feature robotics API

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/auth.py
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/commands/featureflag.py
cognite_toolkit/_cdf_tk/commands/pull.py
cognite_toolkit/_cdf_tk/commands/run.py
cognite_toolkit/_cdf_tk/data_classes/_config_yaml.py
cognite_toolkit/_cdf_tk/data_classes/_project_directory.py
cognite_toolkit/_cdf_tk/loaders/_data_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py
cognite_toolkit/_cdf_tk/prototypes/commands/_changes.py
cognite_toolkit/_cdf_tk/prototypes/commands/import_.py
cognite_toolkit/_cdf_tk/prototypes/commands/modules.py
cognite_toolkit/_cdf_tk/utils.py
tests/data/transformation_cli/manifest_to_asset.Notification.yaml
tests/data/transformation_cli/manifest_to_asset.Schedule.yaml
tests/data/transformation_cli/manifest_to_asset.Transformation.sql
tests/data/transformation_cli/manifest_to_asset.Transformation.yaml
tests/data/transformation_cli/manifest_to_asset.yaml
tests/data/transformation_cli/transformation.sql
tests/tests_unit/test_cdf_tk/test_commands/test_import.py

[CDF-22051]🧑‍🚒Fix transformation-cli import

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/prototypes/robotics_loaders.py
tests/tests_integration/test_loaders/test_resource_loaders.py

[CDF-22052] 🤖Fix robotics deploy

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py

[CDF-22056] 🦠Required container dependency no warning fix

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py

[CDF-22057] 🐜Warning on non-existing parent.

---

cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py
cognite_toolkit/_cdf_tk/prototypes/commands/dump_assets.py

Add limit to asset dump

---

cognite_toolkit/_cdf_tk/tracker.py

[CDF-22064] ⛓️‍💥Mixpannel connection issues

---

.github/workflows/build.yml
CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/client/data_classes/robotics.py
cognite_toolkit/_cdf_tk/prototypes/robotics_loaders.py
poetry.lock
pyproject.toml
tests/tests_integration/test_loaders/test_resource_loaders.py
tests/tests_integration/test_toolkit_client/test_robotics.py

[CDF-22062] 🤖😭

---

cognite_toolkit/_cdf_tk/tracker.py

[CDF-22074]🫣

---

.pre-commit-config.yaml
CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
tests/data/project_no_cognite_modules/modules/another_module/data_models/config.node.yaml
tests/tests_integration/test_commands/test_deploy.py

[CDF-22073]🤡 Complains about node identifier

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py

[CDF-22058] 🙈Fix used i twice

---

cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py
poetry.lock
pyproject.toml
tests/tests_unit/approval_client/client.py
tests/tests_unit/approval_client/config.py
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_files_valhall.yaml
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_timeseries_valhall.yaml
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_functions_dummy.yaml
tests/tests_unit/test_cli/test_build_deploy_snapshots/my_example_module.yaml

[CDF-22071] 👮‍♂️Fixing up function deployment

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/data_classes/_config_yaml.py

fix: catch _build_environment.yaml file missing

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py

[CDF-22122] 🪓Remove import of function check

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/commands/featureflag.py
cognite_toolkit/_cdf_tk/loaders/_base_loaders.py
cognite_toolkit/_cdf_tk/prototypes/modify_function_schedule.py

[CDF-22123]💣Feature flag, change how function schedules are identified. 

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py

[CDF-22124] 🏹Avoid redeploying functions

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/commands/featureflag.py
cognite_toolkit/_cdf_tk/prototypes/create_resource_types.py
cognite_toolkit/_cdf_tk/prototypes/resource_loaders.py
cognite_toolkit/_cdf_tk/prototypes/setup_3D_loader.py
cognite_toolkit/_cdf_tk/prototypes/setup_asset_loader.py
cognite_toolkit/_cdf_tk/prototypes/setup_robotics_loaders.py
cognite_toolkit/cognite_modules/common/cdf_auth_readwrite_all/auth/admin.readonly.group.yaml
cognite_toolkit/cognite_modules/common/cdf_auth_readwrite_all/auth/admin.readwrite.group.yaml
tests/tests_integration/test_loaders/test_resource_loaders.py
tests/tests_unit/test_cdf_tk/test_loaders/test_base_loaders.py
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_auth_readwrite_all.yaml

[CDF-22125] 🤽Support 3D Models

---

cognite_toolkit/_cdf_tk/prototypes/modify_function_schedule.py
cognite_toolkit/_cdf_tk/prototypes/resource_loaders.py
poetry.lock
pyproject.toml
tests/test_integration/test_loaders/test_resource_container_loaders.py
tests/test_integration/test_loaders/test_resource_loaders.py
tests/test_unit/test_cdf_tk/test_parameters/test_functions.py

[CDF-22128] 🤪 Update 3D model fix

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/data_classes/_config_yaml.py
cognite_toolkit/cognite_modules/default.environments.yaml

[CDF-22136] 🙃fix: not raise if name is not existing

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/commands/clean.py
cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/data_classes/_config_yaml.py
tests/test_integration/test_commands/test_deploy.py

[CDF-22112] CDF-22112 Verify deploy --env

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/commands/build.py

[CDF-22127] 👽 Lookup in CDF on build

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
tests/test_integration/test_loaders/test_resource_loaders.py

[CDF-21893, CDF-22132] Fails to update Data Model

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/prototypes/commands/dump_assets.py

[CDF-22139] 🤦 Find metadata columns before start writing to disk

---

CONTRIBUTING.md

[CDF-22140] ✏ Update contribution guideline

---

cognite_toolkit/_cdf_tk/prototypes/commands/dump_assets.py

[CDF-22144] Multifile dump

---

cognite_toolkit/_cdf_tk/tk_warnings/other.py

[CDF-22151] 👨‍✈️ fix: Poor error message

---

cognite_toolkit/_cdf_tk/commands/featureflag.py

[CDF-22154] 😌 Warning about use of feature flags

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/constants.py
cognite_toolkit/_cdf_tk/data_classes/_config_yaml.py
cognite_toolkit/_cdf_tk/prototypes/commands/dump_assets.py
cognite_toolkit/_cdf_tk/prototypes/resource_loaders.py
cognite_toolkit/_cdf_tk/utils.py

[CDF-22153] 🤹 Asset dump

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/prototypes/modify_function_schedule.py

[CDF-22166]🧑‍🚀Fix avoid sending both internal and external id

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/prototypes/commands/import_.py

[CDF-22172] Fix Unicode error

---

CHANGELOG.cdf-tk.md

fix(changelog): added TBD notes about PR#809

---

cognite_toolkit/_cdf_tk/utils.py
tests/test_unit/test_cdf_tk/test_utils.py

Turns out we already had this. Just did a small refactoring.

[CDF-22237] 🫎 Refactor Warning on failed replace environmental variable

---

.github/renovate.json

🌁 Renovate ignore modules requirements files

---

CHANGELOG.templates.md
cognite_toolkit/cognite_modules/examples/cdf_apm_simple_data_model/data_models/6.WorkOrder.view.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_apm_simple_data_model.yaml

Updated version reference to variable reference in example data model.
- [- ] Tests added/updated.
- [Y] Run Demo Job Locally.
- [NA ] Documentation updated.
- [NA] Changelogs updated in [CHANGELOG.cdf-tk.md](https://github.com/cognitedata/toolkit/blob/main/CHANGELOG.cdf-tk.md).
- [NA] Template changelogs updated in [CHANGELOG.templates.md](https://github.com/cognitedata/toolkit/blob/main/CHANGELOG.templates.md).
- [NA] Version bumped.

Fixed version variable reference for linkedAssets and WorkItems 

---

.github/renovate.json

ci: fix try ignore

---

.github/renovate.json

🛑	Not check test directory for dependencies.

---

cognite_toolkit/_cdf_tk/cdf_toml.py
cognite_toolkit/_cdf_tk/constants.py
cognite_toolkit/_cdf_tk/feature_flags.py

[CDF-22441] 🧱 Robustify reading feature flags

---

cognite_toolkit/_cdf_tk/tracker.py
tests/constants.py
tests/test_unit/conftest.py
tests/trigger_mixpanel_event.py

[CDF-22496] 🎸 Instrument feature flag

---

cognite_toolkit/_repo_files/cdf.toml
dev.py

fix: bump command

---

.vscode/launch.json
cognite_toolkit/_cdf_tk/commands/run.py

friendlier message if no functions are found

---

cognite_toolkit/_cdf_tk/utils.py

Changed prompts that were confusing

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py

Remove SDK Warnings

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/workflow_loaders.py

[CDF-22528] 🙄 Support dict workflowtrigger

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py
tests/test_unit/test_cdf_tk/test_loaders/test_group_loader.py

[CDF-22538] 🦛Group without metadata

---

cognite_toolkit/_cdf_tk/utils.py
tests/test_unit/test_cdf_tk/test_utils.py

[CDF-22518] 🧗 GraphQL Parser

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/extraction_pipeline_loaders.py
cognite_toolkit/_cdf_tk/utils.py
tests/test_unit/test_cdf_tk/test_loaders/test_extraction_pipeline_loader.py
tests/test_unit/test_cdf_tk/test_utils.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_3d_valhall.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_asset_valhall.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_files_valhall.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_timeseries_valhall.yaml
tests/test_unit/utils.py

[CDF-22331, CDF-22544] 🐧Extraction Pipeline Config parse config as string

---

cognite_toolkit/_cdf_tk/client/data_classes/location_filters.py
tests/test_integration/conftest.py
tests/test_integration/test_toolkit_client/test_locations.py

[CDF-22579] 😮‍💨Location filter with data models

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/client/data_classes/robotics.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/classic_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/data_organization_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/extraction_pipeline_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/file_loader.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/hosted_extractors.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/three_d_model_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/timeseries_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
poetry.lock
pyproject.toml

Long explanation: https://cognite-sdk-python.readthedocs-hosted.com/en/latest/appendix.html#update-and-upsert-mode-parameter

[CDF-22563] 🧘‍♂️Fix update

---

cdf.toml
cognite_toolkit/_cdf_tk/cdf_toml.py
cognite_toolkit/_cdf_tk/exceptions.py

[CDF-22632] 🦿TOML Error

---

cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/commands/clean.py
cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/constants.py
cognite_toolkit/_cdf_tk/hints.py
cognite_toolkit/_cdf_tk/tk_warnings/fileread.py
cognite_toolkit/_cdf_tk/utils.py
tests/data/complete_org/modules/my_example_module/data_models/location.DataModel.yaml
tests/data/complete_org/modules/my_example_module/data_models/location.Space.yaml
tests/data/complete_org/modules/my_example_module/locations/data_model.LocationFilter.yaml
tests/data/complete_org/modules/my_example_module/locations/data_model_based.LocationFilter.yaml
tests/test_unit/approval_client/client.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_infield_location.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_infield_second_location.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml

* Add test for location filter
Silent skip

[CDF-22635] 🧑‍🏫Location Testing

---

cognite_toolkit/_cdf_tk/hints.py

[CDF-22352] 😶 Added deprecation warning

---

cdf.toml
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/feature_flags.py
cognite_toolkit/_cdf_tk/loaders/__init__.py
cognite_toolkit/_cdf_tk/plugins.py

[CDF-22660] 🙂‍↕️ Setup plugins

---

.github/workflows/build.yml
.github/workflows/demo.yml
CHANGELOG.cdf-tk.md
poetry.lock
pyproject.toml
tests/test_unit/test_cdf_tk/test_parameters/test_type_hint.py

[CDF-22659] 😬 Drop python3.9 support

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/hosted_extractors.py

[CDF-22657] 😔 Handle no .as_write

---

cognite_toolkit/_cdf_tk/commands/_changes.py
module_upgrade/run_check.py

Automatic fix node

---

.github/workflows/prepare-release.yaml
CHANGELOG.cdf-tk.md
dev.py
module_upgrade/run_check.py

[CDF-22638] 🤤 Auto Release

---

cognite_toolkit/_builtin_modules/cdf.toml
cognite_toolkit/_cdf_tk/commands/modules.py
tests/test_unit/test_cdf_tk/test_commands/test_modules.py

[CDF-22682] 🎁 Bootcamp to test

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/auth.py
cognite_toolkit/_cdf_tk/constants.py

[CDF-22683] 🧑‍✈️Auth Verify

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
tests/test_unit/test_cdf_tk/test_commands/test_build.py
tests/test_unit/test_cdf_tk/test_loaders/test_transformation_loader.py

[CDF-22691] 😖Int version in Transformations

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/constants.py

[CDF-22636] 🚴GraphQL Loader Fixes

---

.github/workflows/build.yml
.github/workflows/prepare-release.yaml
dev.py
module_upgrade/run_check.py

🚅Fix autorelase

---

tests/test_unit/test_cdf_tk/test_loaders/test_transformation_loader.py

🙃Added back transformation loader tests

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_data_loaders.py
cognite_toolkit/_cdf_tk/utils.py
tests/data/complete_org/modules/my_example_module/data_models/file_extension.Container.yaml
tests/data/complete_org/modules/my_example_module/data_models/file_extension.View.yaml
tests/data/complete_org/modules/my_example_module/files/extended.CogniteFile.yaml
tests/data/complete_org/modules/my_example_module/files/vanilla.CogniteFile.yaml
tests/test_unit/approval_client/client.py
tests/test_unit/approval_client/config.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_oid_example_data.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml

[CDF-22745] 📦 feat: Upload Cognite Files

---

.gitignore
cognite_toolkit/_cdf_tk/utils.py

[CDF-22684]🥴 Bugfix hashing issue

---

.github/renovate.json

🛑 Stop trying to update docker files

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/builders/_file.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/file_loader.py

[CDF-22785] 🛞 Expansion pattern for CogniteFile

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_builtin_modules/examples/cdf_location_example/locations/example.LocationFilter.yaml
cognite_toolkit/_cdf_tk/client/data_classes/location_filters.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py
tests/data/complete_org/modules/my_example_module/locations/view_based.LocationFilter.yaml
tests/data/load_data/locations/exhaustive.LocationFilter.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml

[CDF-22837] 😱 Bug in Location Filter

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/file_loader.py

[CDF-22832] 🤗 Recognize cognite files by `CogniteFile` and not `.CogniteFile`

---

CHANGELOG.templates.md
cognite_toolkit/_builtin_modules/common/cdf_apm_base/data_models/containers/ApmConfig.container.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_apm_base.yaml

[CDF-22868] 🐋Fix APMConfig container

---

cognite_toolkit/_builtin_modules/package.toml
cognite_toolkit/_builtin_modules/sourcesystem/README.md
poetry.lock
pyproject.toml
tests/test_unit/test_cli/test_packages.py

💀Skeleton for SourceSystem package

---

cognite_toolkit/_builtin_modules/sourcesystem/sap_assets/auth/transformation.Group.yaml
cognite_toolkit/_builtin_modules/sourcesystem/sap_events/auth/transformation.Group.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/sap_assets.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/sap_events.yaml
tests/test_unit/test_cli/test_command_sequences.py

Fix source system modules

---

.gitignore
cognite_toolkit/_cdf.py

build: update sentry

---

cognite_toolkit/_builtin_modules/common/cdf_auth_readwrite_all/README.md
cognite_toolkit/_builtin_modules/common/cdf_auth_readwrite_all/auth/admin.readonly.group.yaml
cognite_toolkit/_builtin_modules/common/cdf_auth_readwrite_all/auth/admin.readwrite.group.yaml
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py
poetry.lock
pyproject.toml
tests/test_unit/test_builtin_modules/test_cdf_auth_readwrite_all.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_auth_readwrite_all.yaml

[CDF-22809] 🔓Dev auth write all

---

cognite_toolkit/_builtin_modules/common/cdf_auth_readwrite_all/auth/admin.readwrite.group.yaml
tests/test_unit/test_builtin_modules/test_cdf_auth_readwrite_all.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_auth_readwrite_all.yaml

Fix all groups

---

cognite_toolkit/_builtin_modules/common/cdf_auth_readwrite_all/auth/admin.readonly.group.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_auth_readwrite_all.yaml

Remove userProfilesAcl

---

cognite_toolkit/_builtin_modules/contextualization/p_and_id_parser/default.config.yaml
cognite_toolkit/_builtin_modules/contextualization/p_and_id_parser/extraction_pipelines/ctx_files_direct_relation_write.config.yaml
cognite_toolkit/_builtin_modules/contextualization/p_and_id_parser/extraction_pipelines/ctx_files_direct_relation_write.yaml
cognite_toolkit/_builtin_modules/contextualization/p_and_id_parser/extraction_pipelines/ctx_files_pandid_annotater.config.yaml
cognite_toolkit/_builtin_modules/contextualization/p_and_id_parser/extraction_pipelines/ctx_files_pandid_annotater.yaml
cognite_toolkit/_builtin_modules/contextualization/p_and_id_parser/extraction_pipelines/ctx_files_pandid_parser.config.yaml
cognite_toolkit/_builtin_modules/contextualization/p_and_id_parser/extraction_pipelines/ctx_files_pandid_parser.yaml
cognite_toolkit/_builtin_modules/contextualization/p_and_id_parser/functions/contextualization_connection_writer/extraction_pipeline.yaml
cognite_toolkit/_builtin_modules/contextualization/p_and_id_parser/functions/contextualization_connection_writer/handler.py
cognite_toolkit/_builtin_modules/contextualization/p_and_id_parser/functions/contextualization_p_and_id_annotater/extraction_pipeline.yaml
cognite_toolkit/_builtin_modules/contextualization/p_and_id_parser/functions/contextualization_p_and_id_annotater/handler.py
tests/test_unit/test_cli/test_build_deploy_snapshots/p_and_id_parser.yaml

[CDF-22979] 😓	Diagram parser round2

---

CHANGELOG.templates.md

build: fix changelog

---

CHANGELOG.templates.md

docs; poste fix

---

cdf.toml
cognite_toolkit/_builtin_modules/contextualization/cdf_p_and_id_parser/extraction_pipelines/ctx_files_pandid_annotater.config.yaml
cognite_toolkit/_builtin_modules/contextualization/cdf_p_and_id_parser/functions/contextualization_p_and_id_annotater/handler.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_p_and_id_parser.yaml

🐛Fix P&ID Annotation

---

CHANGELOG.templates.md
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_assets/transformations/connection/asset_to_asset.Transformation.sql
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_assets/transformations/connection/asset_to_asset.Transformation.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_sap_assets.yaml

[CDF-22944] Asset.parent to asset

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/apps/_core_app.py
demo/config.demo.yaml

[CDF-23032] 🛑 Build stop on error

---

cognite_toolkit/_cdf_tk/apps/_core_app.py

[CDF-22957] 🐘	 Remove redundant warning in CICD

---

cognite_toolkit/_builtin_modules/sourcesystem/cdf_sharepoint/transformations/population/files.Transformation.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_sharepoint.yaml

Deploy quickstart

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/classic_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py

[CDF-23073] 🪱 Fix LocationFilter

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py

[CDF-22720] Support parent external id in location filter

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/extraction_pipeline_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/raw_loaders.py

[CDF-23157] No more complains

---

cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py

[CDF-23132, CDF-23133] 🕵Better error messages on ill defined dependencies

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/auth.py

[CDF-23175] 🚊 Verify question before updating

---

CHANGELOG.templates.md
cognite_toolkit/_builtin_modules/sourcesystem/cdf_pi/module.toml
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_assets/module.toml
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_events/module.toml
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sharepoint/files/upload.CogniteFile.yaml
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sharepoint/module.toml
cognite_toolkit/_cdf_tk/commands/modules.py
cognite_toolkit/_cdf_tk/data_classes/_module_directories.py
cognite_toolkit/_cdf_tk/data_classes/_module_toml.py
cognite_toolkit/_cdf_tk/tk_warnings/__init__.py
cognite_toolkit/_cdf_tk/tk_warnings/other.py
cognite_toolkit/_cdf_tk/utils/repository.py
tests/test_unit/test_cli/test_packages.py

[CDF-23097] 👻 Example data

---

cognite_toolkit/_builtin_modules/cdf_ingestion/auth/workflow.Group.yaml
cognite_toolkit/_builtin_modules/cdf_ingestion/default.config.yaml
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_assets/transformations/connection/asset_to_asset.Transformation.sql
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_events/auth/workflow.Group.yaml
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_events/default.config.yaml
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_events/transformations/connection/operation_to_maintenance_order.Transformation.yaml
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_events/transformations/population/maintenanceOrder.Transformation.yaml
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_events/transformations/population/operation.Transformation.yaml
cognite_toolkit/_cdf_tk/commands/run.py
demo/config.demo.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_ingestion.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_sap_assets.yaml

There is still an issue with one of the transformations that needs follow up with the Transformation team. Suggest we still merge this PR so it does not become outdated. 

[CDF-23189] 🕵 Verify quickstart package

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py
poetry.lock
pyproject.toml
tests/test_unit/test_cdf_tk/test_loaders/test_base_loaders.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_3d_valhall.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_files_valhall.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_timeseries_valhall.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_inrobot_common.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/ice_cream_api.yaml

Fixed missing env var replacement in FunctionLoader

[CDF-23270] 🌿 Bugfix env replacement

---

CHANGELOG.cdf-tk.md

wrong place in changelog

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/run.py

[CDF-22604, CDF-23211, CDF-22701] Local function dev improvements. 

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/auth.py

Not ask when nothing to update

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/loaders/__init__.py

[CDF-23025] 😑Skip non resource yaml on required kind

---

CHANGELOG.cdf-tk.md
cdf.toml
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/data_classes/_build_variables.py
cognite_toolkit/_cdf_tk/data_classes/_built_modules.py
cognite_toolkit/_cdf_tk/data_classes/_module_resources.py
cognite_toolkit/_cdf_tk/feature_flags.py
tests/data/complete_org_alpha_flags/config.dev.yaml
tests/data/complete_org_alpha_flags/modules/to_repeat/classic/my_asset.Asset.yaml
tests/data/complete_org_alpha_flags/modules/to_repeat/data_sets/location.DataSet.yaml
tests/test_unit/test_cdf_tk/test_data_classes/test_build_variables.py
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org_alpha_flags.yaml
tests/test_unit/test_cli/test_command_sequences.py

[CDF-22706] 🥷 Repeat modules 

---

.vscode/launch.json
CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py

[CDF-23338] Notification create/update bug

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/client/api/dml.py
cognite_toolkit/_cdf_tk/client/api_client.py
cognite_toolkit/_cdf_tk/client/data_classes/graphql_data_models.py
cognite_toolkit/_cdf_tk/client/testing.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
tests/data/complete_org_alpha_flags/modules/my_example_module/data_models/AssetHierarchy.GraphQLSchema.yaml
tests/test_integration/test_commands/test_deploy.py
tests/test_unit/approval_client/client.py
tests/test_unit/approval_client/config.py
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org_alpha_flags.yaml

[CDF-23327] 🤠 Preserve DML

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/client/data_classes/streamlit_.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/industrial_tool_loaders.py

Updates to Streamlit apps fixed

[CDF-23379] Streamlit bug

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_builtin_modules/cdf_ingestion/auth/user.Group.yaml
cognite_toolkit/_builtin_modules/cdf_ingestion/auth/workflow.Group.yaml
cognite_toolkit/_cdf_tk/commands/auth.py
cognite_toolkit/_cdf_tk/tk_warnings/__init__.py
cognite_toolkit/_cdf_tk/tk_warnings/other.py
cognite_toolkit/_cdf_tk/utils/auth.py
cognite_toolkit/demo/_base.py
tests/test_unit/test_cdf_tk/test_utils.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_ingestion.yaml

```python
import micropip
micropip.uninstall("prompt-toolkit")
await micropip.install("https://cdn.jsdelivr.net/gh/cognitedata/toolkit@52ac98fdd8c31496fc3b4a1051e3c89396c6dfb7/dist/cognite_toolkit-0.3.13-py3-none-any.whl")
from cognite_toolkit.demo import CogniteToolkitDemo
toolkit = CogniteToolkitDemo()
client_id = ""
client_secret = ""
my_org = "MyOrganizaton"
toolkit.quickstart(my_org, client_id, client_secret)
```

[CDF-23387] 😎 CogIDP service principal

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/constants.py

[CDF-23307] 😄 Better type hint

---

CHANGELOG.templates.md
cognite_toolkit/_cdf_tk/data_classes/_config_yaml.py
tests/test_unit/test_cdf_tk/test_data_classes/test_config_yaml.py

[CDF-23421] Too aggresive lift

---

cdf.toml
cognite_toolkit/_cdf_tk/cdf_toml.py
cognite_toolkit/_cdf_tk/commands/featureflag.py
cognite_toolkit/_cdf_tk/feature_flags.py
cognite_toolkit/_cdf_tk/tracker.py

[CDF-23451]  Rename feature to alpha flags

---

cdf.toml
cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/feature_flags.py
cognite_toolkit/_cdf_tk/loaders/__init__.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/__init__.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
tests/data/complete_org_alpha_flags/modules/my_example_module/data_models/edge.Container.yaml
tests/data/complete_org_alpha_flags/modules/my_example_module/data_models/edge.View.yaml
tests/data/complete_org_alpha_flags/modules/my_example_module/data_models/edge_nodes.Node.yaml
tests/data/complete_org_alpha_flags/modules/my_example_module/data_models/my.Edge.yaml
tests/data/complete_org_alpha_flags/modules/my_example_module/data_models/spaces.Space.yaml
tests/test_unit/approval_client/client.py
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org_alpha_flags.yaml
tests/test_unit/test_cli/test_command_sequences.py

[CDF-23406] 🫣Support edges

---

cognite_toolkit/_builtin_modules/cdf_common/functions/contextualization_connection_writer/handler.py
cognite_toolkit/_builtin_modules/cdf_ingestion/auth/user.Group.yaml
cognite_toolkit/_builtin_modules/cdf_ingestion/auth/workflow.Group.yaml
cognite_toolkit/_builtin_modules/contextualization/cdf_p_and_id_parser/auth/function.Group.yaml
cognite_toolkit/_builtin_modules/contextualization/cdf_p_and_id_parser/functions/contextualization_p_and_id_annotater/handler.py
cognite_toolkit/_cdf_tk/commands/run.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_common.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_ingestion.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_p_and_id_parser.yaml

[CDF-23432]🙄Contextualization Issue

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/utils/graphql_parser.py
tests/test_unit/test_cdf_tk/test_utils.py

[CDF-23402] 😔 GraphQL parser bug

---

cognite_toolkit/demo/_base.py

[CDF-23456] 😺 feat: Better error messages

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/utils/auth.py

[CDF-23413] 👻Remove irrelevant warnings

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/utils/auth.py
tests/test_unit/test_cdf_tk/test_utils.py

[CDF-23390] 😸 Cog IDP fixes

---

CHANGELOG.cdf-tk.md

Fix changelog

---

cognite_toolkit/_cdf_tk/commands/build.py

[CDF-21797] 🙃Print only once

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/builders/_base.py
cognite_toolkit/_cdf_tk/builders/_datamodels.py
cognite_toolkit/_cdf_tk/builders/_file.py
cognite_toolkit/_cdf_tk/builders/_function.py
cognite_toolkit/_cdf_tk/builders/_raw.py
cognite_toolkit/_cdf_tk/builders/_streamlit.py
cognite_toolkit/_cdf_tk/builders/_transformation.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
tests/data/resources_with_environment_variables/modules/example_module/transformations/first.Transformation.yaml
tests/test_unit/test_cdf_tk/test_loaders/test_transformation_loader.py
tests/test_unit/test_cli/test_behavior.py

[CDF-23401] 😊 Transformation sql in build folder

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py
tests/data/complete_org/modules/my_example_module/functions/first.function.yaml
tests/test_unit/test_cdf_tk/test_loaders/test_function_loader.py
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml

[CDF-23535] 👷 Redeploy issue index url

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py

Print graphql model ids

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/utils/graphql_parser.py
tests/test_unit/test_cdf_tk/test_utils/test_graphql_parser.py

[CDF-23536] 🥷 GraphQL Issue

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/utils/auth.py
tests/test_unit/test_cdf_tk/test_utils/test_utils.py

[CDF-23551] 🤨 Config client

---

.pre-commit-config.yaml
CHANGELOG.cdf-tk.md
cdf.toml
cognite_toolkit/_cdf_tk/apps/_core_app.py
cognite_toolkit/_cdf_tk/feature_flags.py
cognite_toolkit/_cdf_tk/utils/cicd.py

[CDF-23572] 🏚 Build offline

---

cognite_toolkit/_cdf_tk/commands/pull.py
cognite_toolkit/_cdf_tk/loaders/_worker.py
cognite_toolkit/_cdf_tk/utils/modules.py

[CDF-23634] 👮 Limit cdf modules pull

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/client/data_classes/sequences.py
cognite_toolkit/_cdf_tk/commands/clean.py
cognite_toolkit/_cdf_tk/loaders/__init__.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/__init__.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/classic_loaders.py
poetry.lock
pyproject.toml
tests/data/complete_org_alpha_flags/modules/my_example_module/classic/power_curve.Sequence.yaml
tests/data/complete_org_alpha_flags/modules/my_example_module/classic/power_curve.SequenceRow.yaml
tests/test_unit/approval_client/config.py
tests/test_unit/test_cdf_tk/test_loaders/test_extraction_pipeline_loader.py
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org_alpha_flags.yaml

 [CDF-23628] 🚣 Sequence rows

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_api/modules_api.py
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/commands/dump.py
cognite_toolkit/_cdf_tk/commands/dump_assets.py
cognite_toolkit/_cdf_tk/commands/dump_timeseries.py
cognite_toolkit/_cdf_tk/commands/modules.py
cognite_toolkit/_cdf_tk/commands/pull.py
cognite_toolkit/_cdf_tk/commands/run.py
cognite_toolkit/_cdf_tk/utils/file.py
module_upgrade/run_check.py

[CDF-23268] 👮Permission Error

---

cognite_toolkit/_cdf_tk/utils/auth.py
tests/auth_utils.py

[CDF-23603, CDF-23620]🔘Transformations issue

---

cognite_toolkit/_cdf_tk/builders/_file.py

[CDF-22881] 🔳Error message invalid use of file template

---

cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/data_classes/_build_variables.py

[CDF-22446, CDF-21929] 🐶Friendly error message

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/file_loader.py
cognite_toolkit/_cdf_tk/tk_warnings/fileread.py

[CDF-23408] 🐻‍❄️ Unused DataSetId

---

cognite_toolkit/_cdf_tk/commands/pull.py
cognite_toolkit/_cdf_tk/constants.py
cognite_toolkit/_cdf_tk/data_classes/_config_yaml.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/extraction_pipeline_loaders.py
cognite_toolkit/_cdf_tk/utils/file.py

[CDF-22517] 🏰  Large yaml files

---

cognite_toolkit/_cdf_tk/builders/_base.py
cognite_toolkit/_cdf_tk/builders/_transformation.py
cognite_toolkit/_cdf_tk/commands/_changes.py
cognite_toolkit/_cdf_tk/commands/dump.py
cognite_toolkit/_cdf_tk/commands/modules.py
cognite_toolkit/_cdf_tk/commands/pull.py
cognite_toolkit/_cdf_tk/commands/run.py
cognite_toolkit/_cdf_tk/data_classes/_module_toml.py
cognite_toolkit/_cdf_tk/data_classes/_packages.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/industrial_tool_loaders.py
cognite_toolkit/_cdf_tk/prototypes/_packages/update_references.py
cognite_toolkit/_cdf_tk/utils/auth.py
cognite_toolkit/_cdf_tk/utils/file.py
tests/data/complete_org/modules/my_example_module/transformations/first.transformation.sql
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml

[CDF-22206] 😷Unicode

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/workflow_loaders.py

[CDF-22300] 😵‍💫 WorkflowVersion spec subworkflow

---

cognite_toolkit/_cdf_tk/tracker.py

If mixpanel fail, do not confuse the user with error messages:

[CDF-22442] 🥵 Mixpanel issue. 

---

cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/tk_warnings/fileread.py

[CDF-23325] 🔄 feat: warning repeated module

---

cognite_toolkit/_cdf_tk/prototypes/commands/import_.py
cognite_toolkit/_cdf_tk/prototypes/import_app.py
tests/test_unit/test_cdf_tk/test_commands/test_import.py

Early feedback on new feature. A bonus is that I think the `--overwrite` flag becomes clearer.

[CDF-21926] 😊 Transformation-cli import clean

---

CHANGELOG.cdf-tk.md

Changelog for PRs
#1253 - #1365

📖 Changelog entries

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/cdf_toml.py
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/hints.py

[CDF-23754] 😊 Config.yaml optional

---

cognite_toolkit/_cdf_tk/commands/modules.py

Very hard issue to recreate as we do not have access to the modules the user reported. This is my best guess what could go wrong.

[CDF-23411] 😃 Report changes

---

CONTRIBUTING.md

Updating release guide

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/_purge.py

[CDF-23656, CDF-23665] 😬 Purge 408 issue and space dependencies

---

.github/pull_request_template.md
cognite_toolkit/_cdf_tk/apps/_purge.py

Purge command help texts

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_data_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/classic_loaders.py
cognite_toolkit/_cdf_tk/utils/file.py
tests/test_integration/test_commands/test_deploy.py

[CDF-23869] ↩ reverted; 0.3.24 read any csv dialect

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/_base.py
cognite_toolkit/_cdf_tk/commands/_purge.py
cognite_toolkit/_cdf_tk/data_classes/_deploy_results.py
cognite_toolkit/_cdf_tk/loaders/_base_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/classic_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/group_scoped_loader.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/hosted_extractors.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/industrial_tool_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/raw_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/workflow_loaders.py
cognite_toolkit/_cdf_tk/tk_warnings/base.py
cognite_toolkit/_cdf_tk/utils/cdf.py
tests/test_integration/test_commands/test_deploy.py
tests/test_integration/test_loaders/test_resource_loaders.py
tests/test_unit/test_builtin_modules/test_cdf_auth_readwrite_all.py

[CDF-23828] 🥴 Instances timeout issue

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/pull.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py

[CDF-23887] ⤵Group/pull issues

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py
tests/test_unit/test_cdf_tk/test_loaders/test_group_loader.py

[CDF-23945] 🐛Groups not recreated

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py
tests/test_unit/test_cdf_tk/test_loaders/test_group_loader.py

[CDF-23946] 😡 Group rawacl diff

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/file_loader.py
tests/test_unit/test_cdf_tk/test_builders/test_builder.py

[CDF-23947] 🐛 Get loader issue

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py

Fix raw dependency

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/utils/auth.py

🔧fix; multiple scopes

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/_purge.py

[CDF-23985]😱Fix not delete node types other spaces

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/_purge.py

[CDF-24077] 😖 Improve error message

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py

[CDF-24115, CDF-23966] 😠 Group fallback one-by-one

---

CHANGELOG.cdf-tk.md
CHANGELOG.templates.md
cognite_toolkit/_builtin_modules/models/cdf_cdm_extension_full/data_models/containers/Annotation.Container.yaml
cognite_toolkit/_builtin_modules/models/cdf_process_industry_extension_full/data_models/containers/360ImageAnnotation.Container.yaml
cognite_toolkit/_builtin_modules/models/cdf_process_industry_extension_full/data_models/containers/Annotation.Container.yaml
cognite_toolkit/_builtin_modules/models/cdf_process_industry_extension_full/data_models/containers/DiagramAnnotation.Container.yaml
cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
tests/test_unit/test_cdf_tk/test_loaders/test_container_loader.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_cdm_extension_full.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_process_industry_extension_full.yaml

[CDF-24120] 😢 Fails to deploy idm extension

---

CHANGELOG.cdf-tk.md
cdf-tk-dev.py
cdf.toml
cognite_toolkit/_cdf_tk/client/_toolkit_client.py
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/commands/clean.py
cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/commands/modules.py
cognite_toolkit/_cdf_tk/data_classes/_config_yaml.py
cognite_toolkit/_cdf_tk/feature_flags.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/workflow_loaders.py
cognite_toolkit/_cdf_tk/utils/auth.py
tests/test_integration/conftest.py
tests/test_integration/test_loaders/test_resource_loaders.py
tests/test_unit/approval_client/client.py
tests/test_unit/test_cdf_tk/test_commands/test_build.py
tests/test_unit/test_cdf_tk/test_data_classes/conftest.py
tests/test_unit/test_cdf_tk/test_loaders/test_function_loader.py
tests/test_unit/test_cdf_tk/test_loaders/test_workflow_loaders.py
tests/test_unit/test_cdf_tk/test_utils/test_auth.py

[CDF-24121] 💂 Strict validation authorization

---

cognite_toolkit/_cdf_tk/prototypes/import_app.py

updating trafo cli command

---

CHANGELOG.cdf-tk.md
cdf.toml
cognite_toolkit/_cdf_tk/feature_flags.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/workflow_loaders.py
cognite_toolkit/_cdf_tk/utils/cdf.py
cognite_toolkit/_cdf_tk/utils/hashing.py
tests/test_unit/approval_client/client.py
tests/test_unit/test_cdf_tk/test_loaders/test_function_loader.py
tests/test_unit/test_cdf_tk/test_loaders/test_transformation_loader.py
tests/test_unit/test_cdf_tk/test_loaders/test_workflow_loaders.py

[CDF-24141] 👻 Credentials hash

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py

[CDF-23962] 😬 View deployment order

---

CHANGELOG.cdf-tk.md

build: changelog entries

---

.github/workflows/release.yaml
dev.py

* Allow Improved in changelog. 
* Skip trying to create changelog if `skip` is selected.
* Improved error message for wrong changelog header.

🤖 Allow Improved Header in Changelog

---

cognite_toolkit/_cdf_tk/loaders/_data_loaders.py
tests/test_unit/test_cdf_tk/test_loaders/test_raw_file_loader.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_example_pump_asset_hierarchy.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_oid_example_data.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml

**NOTE** The last commit is just generated snapshots. The actual PR is +58-1
- When uploading a `csv` file to a RAW table, Cognite Toolkit no longer uses string as the value type independent of the actual value type.
No changes.

[CDF-24290] 🙊 Raw upload issue

---

cognite_toolkit/_builtin_modules/bootcamp/ice_cream_api/functions/icapi_datapoints_extractor/handler.py

Datapoints extractor no longer reporting runs per time series.
No changes.
- bootcamp module: Datapoints extractor no longer reporting runs per time series.

hotfix for extraction pipelines bug/overuse

---

cognite_toolkit/_cdf_tk/resource_classes/event.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_event.py

This PR introduces pydantic model for Event Resource class that matches the YAML file format that toolkit expects.

[CDF-24573] Pydantic Validation for Events

---

cognite_toolkit/_cdf_tk/resource_classes/space.py
tests/data/complete_org/config.dev.yaml
tests/data/complete_org/modules/my_file_expand_module/data_models/file.Space.yaml
tests/data/complete_org/modules/my_file_expand_module/files/my.CogniteFile.yaml
tests/test_unit/test_cdf_tk/test_resource_classes/test_space.py

This PR introduces pydantic model for Space Resource class that matches the YAML file format that toolkit expects.

[CDF-24574] Pydantic Validation for Spaces

---

cognite_toolkit/_cdf_tk/resource_classes/raw_database_table.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_raw_database_table.py

This PR introduces pydantic model for Raw database and table Resource class that matches the YAML file format that toolkit expects.

[CDF-24579] Pydantic Validation for Raw Database and Table

---

dev.py
tests/test_unit/test_toolkit_release_process.py

Allow upper case when in the changelog below in the release process.

Allow upper case

---

dev.py

Description
Fixing release for #1576
- GitHub Action examples now get current Toolkit version
- Upgraded pydantic version
No changes.

Outdated path in dev.py script

---

cdf.toml
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/apps/__init__.py
cognite_toolkit/_cdf_tk/apps/_migrate_app.py
cognite_toolkit/_cdf_tk/feature_flags.py

**Context** We will support multiple migrations through Toolkit. Currently I plan for `timeseries/files/canvas/charts/infield`. This PR sets up the feature flag for migration along with the base command, such that upcoming PRs can stack on top of this one, and thus being independent of each other.

[prep CDF-24931] 😊 Introduce migrate app

---

pyproject.toml
uv.lock

Adds the `sqlparse` dependency. This will be used in the next PR to parse transformation queries to get the source they are writing from.

[prep CDF-24921] 🦈 Add sqlparse

---

.github/CODEOWNERS

Changes the ownership of this repo to partner enalbement

➡Move to partner enablement

---

tests/auth_utils.py

The `get_toolkit_client` is a helper function not part of the package. It is used to debug. 
This fixes a deviation on this helper function vs how Toolkit generally the token login flow to name the variables.

🦾Fix helper

---

cognite_toolkit/_cdf_tk/utils/cdf.py
tests/test_integration/test_utils/test_cdf.py

Fixes bug in SQL causing it to ignore the row count. Note this has not yet been released to end-users, thus no need for a release.

[CDF-25147]🐛 Bug in row count

---

cognite_toolkit/_cdf_tk/utils/table_writers.py
cognite_toolkit/_cdf_tk/utils/useful_types.py

This will be reused in other parts of the code.

🧱 Move out JSON type

---

cognite_toolkit/_cdf_tk/commands/_migrate/data_classes.py
tests/test_unit/test_cdf_tk/test_commands/test_timeseries_migration.py

See below
- [alpha] Running `cdf migrate timeseries --mapping-file my_file.csv` handles BOM character at the beginning of the csv file. 
- [alpha] Running `cdf migrate timeseries --mapping-file my_file.csv` has more informative error messages.
No changes.

[CDF-25263] 💣 Bom character

---

cognite_toolkit/_cdf_tk/apps/_profile_app.py
cognite_toolkit/_cdf_tk/commands/_profile.py
cognite_toolkit/_cdf_tk/utils/interactive_select.py
cognite_toolkit/_cdf_tk/utils/useful_types.py
tests/test_unit/test_cdf_tk/test_utils/test_interactive_select.py

- [alpha] The `cdf profile raw/transformations` will now prompt an interactive select if you do not set destination.
No changes.

[CDF-25241] 🦾	 Interactive selection cdf profile raw/transformations

---

cognite_toolkit/_cdf_tk/utils/interactive_select.py
tests/test_unit/test_cdf_tk/test_utils/test_interactive_select.py

This PR implements interactive selection of spaces/views. This will be used in the upcoming `cdf purge instances` command to select view and instance spaces to purge.

[CDF-25151] 😆 Data modeling interactive select

---

tests/test_integration/test_commands/test_migrate_timeseries.py

I have tried to clean up the `TestMigrateTimeSeriesCommand` test so that the sleep command is no longer necessary.
- Use csv.writer instead of writing strings. For readability.
- Fetch migrated time series by `instance_id` instead of by `external_id`.
- Remove `time.sleep` which is no longer necessary after we fetch by `instance_id`.
- Simplify assert that we migrated the right time series.
No changes.

Clean up TestMigrateTimeSeriesCommand

---

cognite_toolkit/_cdf_tk/commands/build_cmd.py
cognite_toolkit/_cdf_tk/tk_warnings/other.py
tests/test_unit/test_cli/test_behavior.py

In addition to fixing the bug if displaying the error message, I also improved the wording a bit.
- When running `cdf build`, Toolkit now warns about dependencies that are not in CDF and local configuration.
No changes.

[CDF-25266] 😅 Missing dependency

---

.pre-commit-config.yaml
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/agent_loaders.py

I got tired of seeing `legacy`

😄Update ruff id in pre-commit

---

cognite_toolkit/_cdf_tk/commands/_download.py
cognite_toolkit/_cdf_tk/commands/dump_resource.py
cognite_toolkit/_cdf_tk/cruds/_base_cruds.py
cognite_toolkit/_cdf_tk/cruds/_resource_cruds/datamodel.py
cognite_toolkit/_cdf_tk/cruds/_resource_cruds/workflow.py
cognite_toolkit/_cdf_tk/storageio/_selectors.py
cognite_toolkit/_cdf_tk/utils/__init__.py
cognite_toolkit/_cdf_tk/utils/cdf.py
cognite_toolkit/_cdf_tk/utils/file.py
cognite_toolkit/_cdf_tk/utils/fileio/_writers.py
cognite_toolkit/_cdf_tk/utils/table_writers.py
tests/test_unit/test_cdf_tk/test_utils/test_file.py

This has annoyed me for a while, so suggest the renaming to better explain what this small utility function is doing.
Added some test of it as it did not have any.

😠Rename to_directory_compatible

---

.github/CODEOWNERS

Add new Velocity team as the owner.

Added velocity owner
