cognitedata/toolkit

.env.tmpl
.github/workflows/dev.yml
.vscode/launch.json
.vscode/tasks.json
README.md
build.py
deploy.py
local.yaml
scripts/templates.py

build.py and deploy.py now support --env=<local|demo|dev|staging|prod>
Default is dev.
local.yaml supports configuration of environments, so you can deploy different modules dependent on environment.
config.yaml files now support prefixed variables with environment: <env>.my_var allowing you to set vars based on environment
CDF_ENVIRON and CDF_BUILD_TYPE are set as environment variables based on the settings in local.yaml.

Support environments

---

cognite_toolkit/cdf.py
pyproject.toml

The current release crashes on the `example_pump` package as the experimental module is not included.

New alpha release

---

cognite_toolkit/cdf_tk/load.py

Dataset metadata may look like this:
```
- externalId: 'ds_infield_default_app_data'
name: infield:default:app_data
description: This dataset is for writing data from Infield for the location default.
metadata: 
consoleSource:
names:
- '{{source_name}}'
rawTables:
- databaseName: 'asset-{{location_name}}-{{source_name}}'
tableName: 'assets'
transformations:
- externalId: 'tr_asset_{{location_name}}_{{source_name}}_asset_hierarchy'
type: 'jetfire'
```
This PR flattens the metadata values with json since the API expects a dict(str, str)

Added support for nested metadata in datasets

---

CHANGELOG.cdf-tk.md
cognite_toolkit/cdf_tk/templates.py
cognite_toolkit/cdf_tk/utils.py
tests/test_cdf_tk/data/config.yaml
tests/test_cdf_tk/project_configs/cognite_modules/a_module/auth/readonly.all.group.yaml
tests/test_cdf_tk/test_templates.py
tests/test_cdf_tk/test_utils.py

Check for `<change_me>`
```
WARNING: Found the following warnings in config.yaml:
TemplateVariableWarning: Variable 'readwrite_source_id' has value '<change_me>' in file: config.yaml. Did you forget to change it?
TemplateVariableWarning: Variable 'readonly_source_id' has value '<change_me>' in file: config.yaml. Did you forget to change it?
TemplateVariableWarning: Variable 'applicationsconfiguration_source_id' has value '<change_me>' in file: config.yaml. Did you forget to change it?
TemplateVariableWarning: Variable 'infield_default_location_checklist_admin_users_source_id' has value '<change_me>' in file: config.yaml. Did you forget to change it?
TemplateVariableWarning: Variable 'infield_default_location_normal_users_source_id' has value '<change_me>' in file: config.yaml. Did you …
```

Build checks

---

cognite_toolkit/cdf_tk/templates.py

Now prints the following warning:
```
WARNING: In module 'my_example_module', the resource 'timeseries_typo' is not supported by the toolkit.
Available resources are: auth, data_sets, raw, timeseries, transformations, timeseries_datapoints, extraction_pipelines, files, data_models
```
In addition, fix a bug that cause the `cdf-tk build` to skip the `custom_module`

Validation resource type

---

cognite_toolkit/cdf_tk/utils.py

"Softened" the extraction pipeline check since running loaders in sequence should make it unlikely to fail. Hence it shows a warning instead of raising an exception. 

Missing extraction pipeline does not raise exception

---

tests/conftest.py
tests/test_approval_modules.py
tests/test_approval_modules_snapshots/cdf_data_pipeline_asset_valhall.yaml
tests/test_approval_modules_snapshots_clean/cdf_data_pipeline_asset_valhall.yaml
tests/test_cdf_tk/test_load.py

This PR does not do any changes to production code instead testing is changed.
This test runs the three commands `init`, `build` and `deploy` for each module with the `--dry-run` flag set, 
and verifies that no `create` or `delete` calls are made to any of the CDF resources. In addition, it checks that neither `verify_dataset`, `verify_space`, `verify_extraction_pipeline` have been called as these resources might not have been created.
The existing test for deploying each module (`init`, `build`, and `deploy`) is extended to check that all CDF resources have been mocked (so we can log calls and intercept their creation calls). (Same extension for the `init`, `build`, `clean` test). 
If a resource has not been mocked then you get this error message: 
```
AssertionError: The following APIs …
```

[CDF-20466] Dry run Test to Check that Verify_Dataset is not called with --dry-run flag

---

CHANGELOG.cdf-tk.md
CHANGELOG.templates.md
cognite_toolkit/_version.py
cognite_toolkit/cdf.py
cognite_toolkit/cdf_tk/templates.py
cognite_toolkit/environments.yaml
demo/environments.yaml
tests/test_approval_modules.py
tests/test_build.py

Introduced a `build_environment.yaml` in the build folder to track the state used for running the build.

CDF-toolkit version in environments.yaml

---

CHANGELOG.cdf-tk.md
CHANGELOG.templates.md
cognite_toolkit/cognite_modules/infield/cdf_infield_location/data_sets/location_source_data_set.yaml
tests/test_approval_modules_snapshots/cdf_infield_location.yaml

Add datasets to cdf_infield_location that previously were just templats.

CDF-20462: Add data sets to the infield_location module

---

.gitignore
CHANGELOG.cdf-tk.md
CHANGELOG.templates.md
cognite_toolkit/cdf_tk/load.py
cognite_toolkit/cdf_tk/templates.py
cognite_toolkit/cognite_modules/examples/example_pump_asset_hierarchy/transformations/pump_asset_hierarchy-load-collections_pump.schedule.yaml
cognite_toolkit/cognite_modules/experimental/cdf_asset_source_model/transformations/sync-asset_hierarchy_cdf_asset_source_model.schedule.yaml
cognite_toolkit/cognite_modules/experimental/example_pump_data_model/transformations/pump_model-populate-lift_station_pumps_edges.schedule.yaml
cognite_toolkit/cognite_modules/experimental/example_pump_data_model/transformations/pump_model-populate-pump_container.schedule.yaml
tests/test_approval_modules_snapshots/cdf_asset_source_model.yaml
tests/test_approval_modules_snapshots/example_pump_asset_hierarchy.yaml
tests/test_approval_modules_snapshots/example_pump_data_model.yaml
tests/test_approval_modules_snapshots_clean/cdf_asset_source_model.yaml
tests/test_approval_modules_snapshots_clean/example_pump_asset_hierarchy.yaml
tests/test_approval_modules_snapshots_clean/example_pump_data_model.yaml

- Handle duplicate `TransformationSchedules` when loading `Transformation` resources.
- Print table at the end of `cdf-tk deploy` failed with `AttributeError` is a resource 
returned empty. This is now fixed.
- The `cdf-tk build` command no longer gives a warning about missing `sql` file for 
`TransformationSchedule`s.

Bugfix from Testing

---

.pre-commit-config.yaml
cognite_toolkit/cdf_tk/utils.py
poetry.lock
pyproject.toml

Add `mypy` for `utils.py`. 
Principles: 
* It is better to add in mypy in file by file to keep PRs small. 
* I am trying to make as few changes as possible to me compliant with `mypy`, keep it to only changing type hints if possible.

Add mypy Part1

---

CHANGELOG.cdf-tk.md
cognite_toolkit/cdf.py
tests/conftest.py
tests/test_approval_modules.py
tests/test_approval_modules_snapshots/cdf_auth_readwrite_all.yaml
tests/test_approval_modules_snapshots/cdf_data_pipeline_asset_valhall.yaml
tests/test_approval_modules_snapshots/cdf_infield_common.yaml
tests/test_approval_modules_snapshots/cdf_infield_location.yaml

Ref: https://cognitedata.slack.com/archives/C05RW13C6TX/p1703245850911189
From changelog:
- Fixed bug in `cdf-tk deploy` where auth groups with a mix of all and resource scoped capabilities skipped 
the all scoped capabilities. This is now fixed.

Bugfix: Skipping auth

---

.pre-commit-config.yaml

This pull request updates the build process to use mypy instead of dmypy for type checking. The `mypy` command is now used in the `mypy` hook in the build configuration file. This change ensures consistency and improves the overall build process.

Use mypy instead of dmypy

---

CHANGELOG.cdf-tk.md
cognite_toolkit/cdf_tk/utils.py

fix; TypeError: issubclass() arg 1 must be a class

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/bootstrap.py
cognite_toolkit/_cdf_tk/utils.py

Problem if there is no `.env` present and you want to use `cdf-tk auth verify --interactive` the following exception is raised:
```bash
cdf-tk auth verify --interactive
WARNING: No .env file found in current or parent directory.
WARNING Not able to successfully configure a Cognite client. Requirements: CDF_CLUSTER and CDF_PROJECT environment variables or CDF_TOKEN to a valid OAuth2 token.
Traceback (most recent call last):
...
File "C:\Users\AndersAlbert\Projects\internal\cdf-project-templates\cognite_toolkit\_cdf.py", line 633, in auth_verify
ToolGlobals = CDFToolConfig.from_context(ctx)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\AndersAlbert\Projects\internal\cdf-project-templates\cognite_toolkit\_cdf_tk\utils.py", line 163, in from_context
return …
```

[CDF-21089] Avoid raising exception if .env is missing

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/load/_resource_loaders.py

Requiring DataModelingInstances is restrictive for creating spaces. Removing it.

[CDF-21162] Data modeling capabilities

---

cognite_toolkit/_cdf_tk/load/_data_loaders.py
cognite_toolkit/_cdf_tk/load/_resource_loaders.py
cognite_toolkit/_cdf_tk/utils.py
tests/tests_unit/test_api/conftest.py
tests/tests_unit/test_cdf_tk/test_utils.py

Refactoring to prepare for supporting interactive loginflow
Changes:
* Moved out `existing_spaces` and `data_set_id_by_external_id` to a `_cache` variable to make the functions of these clear.
* Removed `_data_set_id` and `_data_set`. They turned out to never be set, thus it is misleading in the ResourceLoaders that they are scoped to a DataSet in the `get_required_capability` call. That will never happen. So I removed them. I think we need to think a bit more about how to setup the toolkit to deal with resource scoped access.
* Refactored the initialization of the client to make it clearer what is going on. 
[pyproject.toml](https://github.com/cognitedata/cdf-project-templ …

[Prep for CDF-21163] Refactor CDFToolConfig

---

.github/workflows/build.yml
pyproject.toml

Now the GitHub action step for creating the report will fail instead of the running the test step if the coverage falls bellow threshold.
Advantage: Threshold is shown in report, and report is shown also when the coverage test falls. 

ci: threshold on action

---

.pre-commit-config.yaml
cdf-tk-dev.py
cognite_toolkit/_cdf_tk/load/_resource_loaders.py
cognite_toolkit/cognite_modules/examples/cdf_data_pipeline_files_valhall/functions/fn_context_files_oid_fileshare_annotation/pipeline.py
tests/tests_unit/test_approval_modules_snapshots/cdf_data_pipeline_files_valhall.yaml
tests/tests_unit/test_cdf_tk/test_load.py
tests/tests_unit/test_cdf_tk/test_utils.py

Why? 
* One less dependency to maintain.
* Ruff written in Rust much much faster to run than black.
Ruff-format is almost 1-1 with black.

Replace black with ruff

---

cognite_toolkit/_cdf_tk/load/_resource_loaders.py
tests_migrations/migrations.py

In addition, to adding the changes to the known breaking changes. I found one more from the `cogniet-sdk` (container properties of type direct relations now requires a `list: false/true` to be set). Patched the `cognite-toolkit` to handle this case.

Migration tests updated

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/templates/_constants.py
cognite_toolkit/_cdf_tk/templates/_templates.py
cognite_toolkit/_cdf_tk/templates/data_classes/_config_yaml.py
cognite_toolkit/_cdf_tk/templates/data_classes/_system_yaml.py
tests/tests_unit/test_behavior.py
tests/tests_unit/test_cdf_tk/project_for_test/config.dev.yaml
tests/tests_unit/test_cdf_tk/project_no_cognite_modules/config.dev.yaml

- Support for specifying `selected_modules_and_packages` as paths and parent paths. For example, you can
now write `cognite_modules/core/cdf_apm_base` instead of just `cdf_apm_base`. This is to support
modules that have the same name but are in different parent directories. In addition, this also better reflects
the structure of the `cognite_modules` and `custom_modules` folder.

[CDF-21405] Modules selected by path

---

cognite_toolkit/_cdf_tk/load/_base_loaders.py

Maybe against better judgment, changing the base url to one that can be tested for correct HTTP status codes but may become obsolete. 

Setting canonical base url

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/pull.py
cognite_toolkit/_cdf_tk/utils.py

There is also a temporary directory when you use the `cdf-tk init --upgrade` command, but that is never deleted which I think is intentional. As it is up to the user to cleanup when she/he is happy with the upgrade.

[CDF-20990] Cleanup temporarily build directory 🧹

---

CHANGELOG.cdf-tk.md
CHANGELOG.templates.md
cognite_toolkit/_cdf_tk/load/_resource_loaders.py
cognite_toolkit/cognite_modules/examples/cdf_data_pipeline_files_valhall/functions/functions.yaml
cognite_toolkit/cognite_modules/examples/cdf_functions_dummy/functions/functions.yaml

This is a deviation from the API Spec of functions, but I think it is a good reason for an exception.

[CDF-21220] File id not required 🔓

---

cognite_toolkit/_cdf_tk/_parameters/data_classes.py
cognite_toolkit/_cdf_tk/templates/_templates.py
cognite_toolkit/_cdf_tk/validation/__init__.py
cognite_toolkit/_cdf_tk/validation/read_yaml.py
cognite_toolkit/_cdf_tk/validation/warning/__init__.py
cognite_toolkit/_cdf_tk/validation/warning/_base.py
cognite_toolkit/_cdf_tk/validation/warning/fileread.py
cognite_toolkit/cognite_modules/examples/cdf_apm_simple_data_model/data_models/1.Asset.container.yaml
tests/tests_unit/test_cdf_tk/test_parameters/tests_parameters.py
tests/tests_unit/test_cdf_tk/test_validation/test_read_yaml.py

The final goal of #525, #527, #528, #532
This implements the parameter comparison into the build step, which now gives you detailed feedback on the yaml format.
In the above image, I have removed `externalId` from the container, misspelled `name` as `nam`, used snake case instead of camel case on `defaultValue`. Misspelled `list` in two different properties as `lit`.

[CDF-20808, CDF-20999] Warning on bad config ⚠

---

cognite_toolkit/_api/modules_api.py
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/build.py
cognite_toolkit/_cdf_tk/pull.py
cognite_toolkit/_cdf_tk/run.py
cognite_toolkit/_cdf_tk/templates/__init__.py
cognite_toolkit/_cdf_tk/templates/_templates.py
cognite_toolkit/_cdf_tk/templates/data_classes/_base.py
cognite_toolkit/_cdf_tk/user_warnings.py
tests/tests_unit/test_cdf_tk/test_load.py
tests/tests_unit/test_cdf_tk/test_templates.py
tests/tests_unit/test_cli/test_behavior.py

* Created `build.py` module with `BuildCommand` class
* Moved the two functions `build_config` and `process_config_files` from `cognite_toolkit._cdf_tk.templates._templates`, so they can take advantage of the `self.warn` method in the `BuildCommand` class.
* Introduced three generic warnings intended for one-time use.
This is a part 1, will make a Part 2 standardizing and moving the remaining relevant functions from `cognite_toolkit._cdf_tk.templates._templates` into the `build.py` module.

🏠 Build Command to Class with Standardized Warnings Part 1

---

tests/tests_integration/test_loaders/test_resource_container_loaders.py
tests/tests_integration/test_loaders/test_resource_loaders.py

I think this should take care of the flaky test. 
Note since we now run tests in a parallel adding some extra sleep is unlikely to have any impact on the overall time it takes to run the test suite.

🔨 Fixing flaky tests

---

CHANGELOG.templates.md
cognite_toolkit/_cdf_tk/load/_resource_loaders.py
cognite_toolkit/cognite_modules/examples/cdf_data_pipeline_files_valhall/functions/functions.yaml
cognite_toolkit/cognite_modules/examples/cdf_data_pipeline_timeseries_valhall/functions/functions.yaml
cognite_toolkit/cognite_modules/examples/my_example_module/functions/first.function.yaml
tests/tests_unit/test_cdf_tk/test_load.py

In addition to bugfix, found a few unecessary `fileId= <will_be_generated>` that could be removed.
Note that this bug has not been released, so no need for an update in the changelog.

[CDF-21529] 🦗Warning on non required 

---

cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/commands/__init__.py
cognite_toolkit/_cdf_tk/commands/_base.py
cognite_toolkit/_cdf_tk/commands/clean.py
cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/load/_base_loaders.py
tests/tests_integration/test_loaders/test_resource_loaders.py
tests/tests_unit/test_cdf_tk/test_load.py

This PR is an almost pure moving code
* Moved the `deploy_resources` and `clean_resources` from the Loader classes to their respective commands. This makes the loader classes closer to pure interfaces, and keep the responsibility of the deploy and clean operations in the command classes. 
* In addition, found a few custom warning prints, `print("    [yellow]Warning[/yellow] ...")`, which I replaced with a `self.warn` call to standardize them.

[CDF-21568, CDF-21569] 🪓Move deploy and clean

---

poetry.lock
pyproject.toml

To avoid causing issuse if someone has a lower bound on typer that is higher than our upper.

🪸 Loosen upper bound on typer

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/_parameters/data_classes.py
cognite_toolkit/_cdf_tk/load/_resource_loaders.py
cognite_toolkit/_cdf_tk/load/data_classes.py
cognite_toolkit/_cdf_tk/validation.py
tests/tests_unit/test_cdf_tk/test_load.py

Added support for giving nodes as a single dict or list with and without API call parameters
```yaml
space: my_space
externalId: my_node_id
```
```yaml
- space: my_space
externalId: reservoir_type
``` 
Refactoring:
* Did a simplification were I store the APICall parameter on the list instead of the individual nodes, removing the need for the  
`LoadedNode` class, in favor of the more explicitly named `NodeApplyListWithCall`.

[CDF-21507] 🗨 Support node types

---

CHANGELOG.cdf-tk.md
CHANGELOG.templates.md
cognite_toolkit/_cdf_tk/commands/clean.py
cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/load/_resource_loaders.py
cognite_toolkit/cognite_modules/examples/my_example_module/timeseries/my_subscription.DatapointSubscription.yaml
tests/tests_unit/test_cdf_tk/test_load.py
tests/tests_unit/test_cli/test_build_deploy_snapshots/my_example_module.yaml

Turns out rich print actually modifies the input strings, I got the following error message:
Which is now fixed to give the actual correct error message:
Also fixed the issue in the datapoint subscription. 
And also fixed this to not give the folder name, but the display name of the loader

[CDF-21621] 😕 Fixes in printout and demo deployment

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py
tests/tests_unit/test_cdf_tk/test_loaders.py

Leads to this type of output complaining about `spaceIds` and `ids`, instead of the actual.
In addition, added testing for the four most complex logics `ViewLoader`, `ExtractionPipelineLoader`, `TransformationLoader` and `GroupLoader` and found a few more issues.

[CDF-21640]🐛 Bug in checking dependent Groups

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py
tests/tests_unit/test_cdf_tk/test_load.py

The `hasData` filter is a special case when the SDK implementation deviates from the API spec and thus needs special handling. I forgot this in the original implementation. 

[CDF-21639, CDF-21644]🧑‍🚒Warning on valid HasData filter

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/templates/data_classes/_system_yaml.py

Before this PR you get this PR, even though you did not select the modules using these variables thus cluttering the warnings.

[CDF-21656] 🤾Only warnings on selected

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py
tests/tests_unit/test_cdf_tk/test_loaders.py

In the NodeLoader you can get a situation where you create a capability with no SpaceIds in the scope, which is interpreted as no capabilities. And you get an error mesasge `ValueError: No capabilities given`

[CDF-21690] 🕸Handle empty items when checking capabilities

---

tests/tests_integration/test_loaders/test_resource_loaders.py

Increasing time to give the server more time to update.
Improved error message when the retrieve is not returned, so instead of `IndexError: list index out of range`, you will now get `Function schedule not found after update.`

[CDF-21681, CDF-21688]😨 Fix flakey tests

---

cognite_toolkit/_cdf_tk/utils.py

Currently when you call `cdf-tk build cognite_toolkit` the `iterate_modules` function searches **all** directories for modules,
including the code directories `_cdf-tk` and `_api`. Instead of just `cognite_modules`, `custom_modules` and `modules`. This goes wrong if you have a project with the `modules` folder on the root level as then `.github` folder is considered a module as it contains `workflows` subdirectory.

[CDF-21721] 😰Iterate modules bug

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py

[CDF-21717]😕 Container server vs local comparisson

---

cognite_toolkit/_cdf_tk/_migration.yaml
cognite_toolkit/_cdf_tk/data_classes/_base.py
cognite_toolkit/_cdf_tk/data_classes/_migration_yaml.py

[CDF-21667] 😮fix: error message on wrong version

---

cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/exceptions.py

If not source modules are found:
And instead of the following when running the `cdf-tk build`
with this one

[CDF-21480] 🏂Better build message

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/auth.py

[CDF-21487] 🗨Error message not activated function

---

cognite_toolkit/_cdf_tk/data_classes/_config_yaml.py

If you run the old init, no feature flags, you include the prototype variables in the `config.<env>.yaml`. This fixes it.

[CDF-21798] 🤓Do not include prototype variables in old init

---

cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/tk_warnings/fileread.py
tests/tests_unit/test_cdf_tk/test_commands/test_build.py

Today you get:
Replaces it with:

[CDF-21776]  👲Error message when wrong kind

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/commands/auth.py
cognite_toolkit/_cdf_tk/utils.py
cognite_toolkit/cognite_modules/common/cdf_auth_readwrite_all/auth/admin.readwrite.group.yaml
tests/tests_unit/test_cdf_tk/test_commands/test_auth.py
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_auth_readwrite_all.yaml

Multiple bugs in Auth Verify, `cdf-tk auth verify`
If no .env file or --cluster or --cdf-project passed in
The interactive flag is not properly respected, as you also have to input `--group-file` and `--update-group` to control the behavior of the questions being asked. Also not really sure if it is possible to get the `--update-group` path.
Rewrote logic and updated information printed to the terminal.
The `client.functions.activate` call had been lost in refactorings.
```bash
$ cdf-tk auth verify --interactive
Checking current service principal/application and environment configurations...
CDF project cluster (e.g. westeurope-1)?  (bluefield): 
CDF project URL name (e.g. publicdata)?  (albert): 
CDF URL?  (https://bluefield.cognitedata.com): 
Login flow? …
```

[CDF-21790] 🚣 Fix auth verify

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/loaders/_base_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py
cognite_toolkit/_cdf_tk/utils.py

When running `cdf-tk deploy --verbose` gives a detailed output
Note that this PR makes it clear that there are more bugs in the change logic, which appears when you run in `--dry-run` mode.
Creating a separate issue for that.

[CDF-21903]🦸Diffs

---

cognite_toolkit/_cdf_tk/commands/_base.py
cognite_toolkit/_cdf_tk/tk_warnings/__init__.py
cognite_toolkit/_cdf_tk/tk_warnings/base.py
cognite_toolkit/_cdf_tk/tk_warnings/fileread.py
cognite_toolkit/_cdf_tk/tk_warnings/other.py

Make it clear what part of the text belongs to the same warning.

[CDF-21949] 🫤Nice indent

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py
cognite_toolkit/_cdf_tk/prototypes/resource_loaders.py

The `.load_resource` and `_are_equal` can likely be made generic. This will save a lot of code lines, ensure consistent implementations, but will add an extra abstraction layer and thus causing obfuscation. I chose thus to do this the repetitive way

[CDF-21917]🕵️‍♂️ Fix diffs deploy --dry-run

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/constants.py
tests/data/run_data/cognite_modules/examples/run_local_functions/functions/fn_test2/part_of_code.yaml
tests/data/run_data/cognite_modules/examples/run_local_functions/functions/functions.yaml
tests/data/run_data/config.dev.yaml
tests/tests_integration/test_loaders/test_resource_container_loaders.py

Now removed as there is already a config for this function.
This PR contains a larger refactoring in addition to the change above. The motivation for this is that to implement the logic required to figure out whether to give that warning or not, you cannot just look at an individual file as was done before. I realized that the way file and function files were processed did not make sense, so restructured. Notice that a side effect is that you can now have function config in different files, which you could not do before. 

[CDF-21945] 😫Less Warnings on Functions

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/commands/featureflag.py
cognite_toolkit/_cdf_tk/prototypes/turn_off_naming_check.py

[CDF-21946] 🤷Turn off naming convention

---

poetry.lock
pyproject.toml

`packaging` updated to `24.0` in March 2024, not all other packages have upgraded this:
Went through the changelog of `packaging`, and in our use of it (parsing versions) it is safe to downgrade to version `22.0` 

[CDF-21964] 🔻Lower bound for packaging dependency

---

cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/constants.py
cognite_toolkit/_cdf_tk/loaders/_data_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders.py
tests/tests_unit/test_cdf_tk/test_commands/test_build.py
tests/tests_unit/test_cdf_tk/test_loaders/test_base_loaders.py
tests/tests_unit/test_cdf_tk/test_loaders/test_file_metadata_loader.py
tests/tests_unit/test_cli/test_build_deploy_snapshots/cdf_oid_example_data.yaml

[CDF-21984] 🧑‍🚒 Lost SQL files

---

cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/commands/featureflag.py
cognite_toolkit/_cdf_tk/prototypes/commands/__init__.py
cognite_toolkit/_cdf_tk/prototypes/commands/dump_assets.py
cognite_toolkit/_cdf_tk/prototypes/commands/dump_timeseries.py
cognite_toolkit/_cdf_tk/prototypes/resource_loaders.py

- added `DumpTimeSeriesCommand` through copy/paste search/replace approach from `DumpAssetCommand`
- removed the `group` hierarchy-logic which caused some adoption (cannot think of a grouping feature, beside datasets?)
- removed all `label` related code, as timeseries is not supporting labels
- improved interactive mode 
- listing datasets or assets with `clear-name (external_id) [count]`
- added an "Abort" option
- TODO: (left TODO comments in code too)
1. [x] naming convention timeseries, time_series, how to use singular vs plural [DONE]
2. [x] assetId needs externalId replace [DONE]
- so only storing `externalId` in `self.asset_by_id` not the whole `as_write()` object
4. [x] ~~put it under ASSET feature flag support, let me know how to do it, maybe changing ASSETS feature to DUMP?~~
- …

Adding 'dump timeseries' command 

---

cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/data_classes/__init__.py
cognite_toolkit/_cdf_tk/data_classes/_config_yaml.py
cognite_toolkit/_cdf_tk/data_classes/_module_directories.py
cognite_toolkit/_cdf_tk/data_classes/_modules_directories.py
cognite_toolkit/_cdf_tk/data_classes/_system_yaml.py
tests/data/__init__.py
tests/data/project_no_cognite_modules/config.dev.yaml
tests/data/project_no_cognite_modules/config.top_level_variables.yaml
tests/data/project_no_cognite_modules/modules/another_module/data_models/config.node.yaml
tests/test_unit/test_cdf_tk/test_commands/test_build.py
tests/test_unit/test_cdf_tk/test_data_classes/conftest.py
tests/test_unit/test_cdf_tk/test_data_classes/test_build_config_yaml.py
tests/test_unit/test_cdf_tk/test_data_classes/test_config_yaml.py
tests/test_unit/test_cdf_tk/test_data_classes/tests_module_directories.py
tests/test_unit/test_cdf_tk/test_loaders/test_base_loaders.py
tests/test_unit/test_cdf_tk/test_utils.py
tests/test_unit/test_cli/test_behavior.py

Introduced classes `ModuleDirectories` which is a tuple of `ModuleLocation`. This is to deal with all logic of identifying modules, which one are selected, and then have an easier way of running the validation. 
This is in preparation of rewriting variables.

[Prepare CDF-21906] 🦌Simplify Variables (Refactor) Part 1

---

cognite_toolkit/_cdf_tk/commands/_base.py
cognite_toolkit/_cdf_tk/exceptions.py
tests/test_unit/test_cdf_tk/test_commands/test_deploy.py

Getting an error message like this was confusing for the user.
This is caused by the user self by setting
```yaml
source: 
```
in a `View Property`. When you specify `source` you need to give a `ViewId`.
```yaml
source:
space: my_space
externalId: my_external_id
version: 1
type: view
```
Gives the correct Type of error
This is still not a good solution, but it is a larger effort to give a better error message. And there are multiple paths forward
1. Fix in deploy step, try to find out which part of the input is of type `ViewId` and currently set to `None`. 
2. Fix in build step, detect this at the build step and give an appropriate warning.
3. Fix in Python SDK, by handling None values.
All out of scope for what I think we should do in 0.2.x …

[CDF-22192] 👨‍✈️Handle TypeError

---

cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/commands/pull.py
cognite_toolkit/_cdf_tk/data_classes/_build_variables.py
cognite_toolkit/_cdf_tk/data_classes/_config_yaml.py
cognite_toolkit/_cdf_tk/data_classes/_module_directories.py
cognite_toolkit/_cdf_tk/data_classes/_system_yaml.py
cognite_toolkit/_cdf_tk/exceptions.py
cognite_toolkit/_cdf_tk/hints.py
cognite_toolkit/_cdf_tk/validation.py
tests/test_unit/test_cdf_tk/test_loaders/test_base_loaders.py
tests/test_unit/test_cdf_tk/test_utils.py

Use `Path` instead of `tuble[str, ...]` to represent a path.

[CDF-21906] 🫏 Rewrite Variables Part 3

---

.devcontainer/Dockerfile

This pull request fixes the locale for git by generating the necessary locale for pre-commit and git commit. The patch includes the installation of locales and the addition of "en_US.UTF-8 UTF-8" to /etc/locale.gen, followed by running locale-gen.

Fix locale for git in devcontainer

---

cdf.toml
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/cdf_toml.py
cognite_toolkit/_cdf_tk/commands/featureflag.py
cognite_toolkit/_cdf_tk/feature_flags.py
pyproject.toml
tests/test_unit/test_cdf_tk/test_commands/test_feature_flags.py

Feature flags are now loaded form `cdf.toml` instead of temporary file. 
Removed the commands to `cdf featureflags set` and `set featureflag reset` as they are no longer relevant as the user can set the flags directly.

[CDF-22374] 🦈Move Feature Flag into cdf.toml

---

.gitignore
.vscode/launch.json
CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/apps/_modules_app.py
cognite_toolkit/_cdf_tk/commands/modules.py

[CDF-22341] 🏗️ modules init --all (--clean) copies all files from _builtin_modules to org_dir/modules

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/cdf_toml.py

🐛fix: pick up default org in cdm.toml

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/cdf_toml.py
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/commands/modules.py
cognite_toolkit/_cdf_tk/commands/run.py
cognite_toolkit/_cdf_tk/hints.py

**Note**: `cognite_modules` and `custom_modules` are still valid, but not mentioned in the hints any more. This is for clarity. 
And if the modules folder is found in a subdirectory

[CDF-22527] 🧑‍🤝‍🧑Userfriendly message if modules and config not found.

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/_changes.py
cognite_toolkit/_cdf_tk/commands/modules.py
cognite_toolkit/_cdf_tk/constants.py
module_upgrade/run_check.py

* Added missing change between `0.3.0a1` -> `0.3.0a3`.
* Upgraded `modules_upgrade/run_check.py` script to use the `modules init` for versions after `0.3.0a1`.
* Changed to only run migration from `0.2.20` and up until today. We have tested from `0.1.0` to `0.3.0a1` so we know the auto migration works.
* Found a sneaky bug in the `0.3.0a3` creation of `cdf.toml`. 

[CDF-22526] 🤸‍♂️ Migration Fix

---

.github/workflows/build.yml
.github/workflows/demo.yml
CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/apps/__init__.py
cognite_toolkit/_cdf_tk/apps/_auth_app.py
cognite_toolkit/_cdf_tk/commands/_changes.py
cognite_toolkit/_cdf_tk/commands/auth.py
cognite_toolkit/_cdf_tk/loaders/_base_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/asset_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/data_organization_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/extraction_pipeline_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/file_loader.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/raw_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/robotics_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/three_d_model_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/timeseries_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/workflow_loaders.py
cognite_toolkit/_cdf_tk/utils.py
poetry.lock
tests/test_unit/test_cdf_tk/test_commands/test_auth.py
tests/test_unit/test_cdf_tk/test_utils.py

More or less the same as the old `auth verify`, but based on the required loaders capabilities and not the admin group.  Thus, a simpler interface of only one flag `--dry-run`
The previous `cdf auth verify` could end up removing existing capabilities, the new version ensures it is only adding.
As the commands are interactive the testing is outdated. I have done manually testing and set the existing tests to skip. Suggest we move this to the backlog as rewriting the tests to work with interactive is a significant effort. In addition, there is more refactoring that can be done as interactive is now an assumption, but trying to limit the scope of this PR to not do more changes than necessary.
[_version.py](https://github.com/cognitedata/toolkit/blob/main/cognite/cognite_toolkit/_version.py) …

[CDF-21821, CDF-21860, CDF-22355] Split auth in inti and verify

---

.gitignore
CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/cdf_toml.py
cognite_toolkit/_cdf_tk/commands/_changes.py
cognite_toolkit/_cdf_tk/commands/modules.py
cognite_toolkit/_cdf_tk/constants.py
module_upgrade/run_check.py

* Fixed the `python modules_upgrade/run_check.py` script. It was not testing properly and thus giving a false sense of security.
* Located the bug which is we changed `cdf.toml` location from `_repo_files` to `_builtin_modules` and forgot to update the automatic script.
* Found one more bug if you have `plugin` in your `cdf.toml`.

[CDF-22634] 🐛 Migration from 0.2.x to 0.3 alpha

---

poetry.lock
pyproject.toml

Ensures that we support `notificationConfig` in ExtractorPipelines

[CDF-22879] Lower bound cognite-sdk >=7.63.5

---

cognite_toolkit/_repo_files/GitHub/.github/workflows/build.yaml
cognite_toolkit/_repo_files/GitHub/.github/workflows/deploy.yaml

The volume mounted wasn't doing anything. The build and deploy jobs work correctly without providing mount volumes.

Removing invalid volumes mount in the default github workflow

---

cognite_toolkit/_cdf_tk/utils.py
tests/test_unit/test_cdf_tk/test_utils.py

This goes into a larger problem of layers of ENVs, but is a quick fix for local tests

small fix to avoid mixup between environments

---

CHANGELOG.templates.md
cognite_toolkit/_builtin_modules/inrobot/cdf_inrobot_common/default.config.yaml

Variables that belong in the `cdf_apm_base` module were left in  the default.config.yaml of `cdf_inrobot_common`

residue variables

---

cognite_toolkit/_builtin_modules/sourcesystem/cdf_pi/module.toml
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_assets/module.toml
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_events/module.toml
cognite_toolkit/_builtin_modules/sourcesystem/cdf_sharepoint/module.toml
cognite_toolkit/_cdf_tk/commands/modules.py
cognite_toolkit/_cdf_tk/utils/repository.py

New file loader supports these (in addition to GH):
```
[[data]]
repoType = "http"
repo = "https://apps-cdn.cogniteapp.com/toolkit"
source = "publicdata/valhall_file_metadata.csv"
destination = "raw/files.Table.csv"`
```
```
[[data]]
repoType = "http"
repo = "https://apps-cdn.cogniteapp.com/toolkit/publicdata/files"
source = "PH-25578-P-4110006-001.pdf;PH-25578-P-4110010-001.pdf;PH-25578-P-4110119-001.pdf;PH-ME-P-0003-001.pdf;PH-ME-P-0004-001.pdf;PH-ME-P-0151-001.pdf;PH-ME-P-0152-001.pdf;PH-ME-P-0153-001.pdf;PH-ME-P-0156-001.pdf;PH-ME-P-0156-002.pdf;PH-ME-P-0160-001.pdf;Processed-PH-25578-P-4110006-001.svg;Processed-PH-25578-P-4110010-001.svg;Processed-PH-ME-P-0152-001.svg;Processed-PH-ME-P-0153-001.svg;Processed-PH-ME-P-0156-001.svg;Processed-PH-ME-P-0156-002.svg;Processed-PH-ME-P-0160-00 …
```

[CDF-23393] HTTP download support

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/apps/_purge.py
cognite_toolkit/_cdf_tk/commands/_purge.py
cognite_toolkit/_cdf_tk/loaders/_base_loaders.py
cognite_toolkit/_cdf_tk/loaders/_data_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/classic_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/data_organization_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/extraction_pipeline_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/file_loader.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/group_scoped_loader.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/hosted_extractors.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/industrial_tool_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/raw_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/relationship_loader.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/robotics_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/three_d_model_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/timeseries_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/workflow_loaders.py

[CDF-23474] 💥 Purge round 2

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/data_classes/_build_variables.py
tests/test_unit/test_cdf_tk/test_data_classes/test_build_variables.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_common.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_3d_valhall.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_files_valhall.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_timeseries_valhall.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_entity_matching.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_p_and_id_parser.yaml

[CDF-23462] 🥲 Missing quotes

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/builders/_transformation.py
cognite_toolkit/_cdf_tk/commands/pull.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
tests/data/complete_org/modules/my_example_module/transformations/inline.Transformation.yaml
tests/test_unit/test_cli/test_behavior.py
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml

[CDF-23514] 🎢 Inlined transformation

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/utils/graphql_parser.py
tests/test_unit/test_cdf_tk/test_utils/test_graphql_parser.py

[CDF-23515] 🤔GraphQL Comment issue

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/client/api/lookup.py
cognite_toolkit/_cdf_tk/client/data_classes/location_filters.py
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py
tests/data/complete_org/modules/my_example_module/data_models/location.DataModel.yaml
tests/data/complete_org/modules/my_example_module/locations/data_model_based.LocationFilter.yaml
tests/test_integration/test_toolkit_client/test_locations.py
tests/test_unit/approval_client/client.py
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml

[CDF-23605, CDF-23607, CDF-23606] 🤨 Location filter issues

---

tests/data/complete_org/modules/my_example_module/extraction_pipelines/hamburg.config.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml

Seems to no longer be an issue after we started to read the `config` field carefully. Extending test case to include this one.

[CDF-22779] 🕵 Invalid escape sequence

---

cognite_toolkit/_cdf_tk/client/_toolkit_client.py
cognite_toolkit/_cdf_tk/commands/auth.py

No activation of functions on private link projects for `cdf auth verify/init`

[CDF-22714] 🦡 Skip function activation

---

CHANGELOG.templates.md
cognite_toolkit/_builtin_modules/inrobot/cdf_inrobot_location/robotics/root.Frame.yaml
cognite_toolkit/_builtin_modules/inrobot/cdf_inrobot_location/robotics/root.Location.yaml
cognite_toolkit/_builtin_modules/inrobot/cdf_inrobot_location/robotics/root.Map.yaml

[CDF-23755] 🤖 Robotics issue

---

cognite_toolkit/_cdf_tk/commands/dump.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
cognite_toolkit/_cdf_tk/utils/__init__.py
cognite_toolkit/_cdf_tk/utils/cdf.py
tests/test_unit/test_cdf_tk/test_loaders/test_view_loader.py
tests/test_unit/test_cli/test_behavior.py

The API now supports a new `includeInheritedProperties` parameter which makes the lookup of parent obsolete for converting from read to write format.

[prep CDF-23388] 👷 Use new view retrieve parameter

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/utils/hashing.py
tests/test_unit/test_cdf_tk/test_commands/test_build.py

[CDF-23957] 🧐 Robustify hash calculation

---

CHANGELOG.cdf-tk.md
cognite_toolkit/_cdf_tk/commands/_purge.py
cognite_toolkit/_cdf_tk/exceptions.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/classic_loaders.py
cognite_toolkit/_cdf_tk/utils/collection.py

Tested with an asset hierarchy of 100,000:
**Note** Ideally we should have a `cdf purge asset` command that selects an hierarchy. 

[CDF-23917] 🤯 Purge Asset Hierarchy

---

cognite_toolkit/_repo_files/GitHub/.github/workflows/build.yaml

See https://github.com/cognitedata/toolkit-demo/pull/75 for demo
Features:
* Looks up the previous comment, such it keeps updating the same comment instead of creating a new one for each commit.
* Stores both the build and dry run output.

[CDF-22937] 🤖 Feat: added comment on PR

---

cognite_toolkit/_cdf_tk/utils/auth.py
tests/test_unit/test_cdf_tk/test_utils/test_auth.py

There were no way to set ENV variables to authenticate with CDF as the provider.
You can use CDF as the provider if you set your env file to 
```env
LOGIN_FLOW=client_credentials
PROVIDER=cdf
CDF_CLUSTER=
CDF_PROJECT=
IDP_CLIENT_ID=
IDP_CLIENT_SECRET=
```
We are not exposing this to the end user as this is only in private alpha used by GSS.

[CDF-24185] 🚓 Allow CDF auth provider

---

cognite_toolkit/_cdf_tk/client/api/lookup.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py
tests/test_integration/test_loaders/test_resource_loaders.py

We no longer raise an error when looking up external IDs from internal IDs. Instead we give a warning. The reasoning is that every time we look up an external ID from internal, it is from a resource already deployed to CDF and not a user fault in local configuration. Thus, we give warning instead.
- When running `cdf deploy/pull`, the Toolkit no longer raise an `ResourceRetrievalError` if a CDF resource is referencing a non-existing resource. For example, if a group has an `TimeSeriesAcl` scoped to a timeseries that no longer exists. 
No changes.

Missing internal ID lookup 

---

cognite_toolkit/_cdf_tk/utils/file.py
tests/test_unit/test_cdf_tk/test_data_classes/test_config_yaml.py

Module defaults that caused long lines got unwanted line breaks: 
```
data_developer_source_id: <OBJECT ID FOR TEST/PROD DATA DEVELOPER ENTRA GROUP> # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
```
turned into 
```
data_developer_source_id: <OBJECT ID FOR TEST/PROD DATA DEVELOPER ENTRA  # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
GROUP>
```
This is now fixed
- Fixed a bug that caused unwanted line breaks in module default values
No changes.

[CDF-24289 ] extending line width when dumping yaml to avoid unwanted line breaks

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py

I did some experimenting on a case, and ended up having to delete and recreate the test containers. This triggered the following bug, which is currently causing the tests on the main branch to fail.
**Risk Reviewer** As this is currently blocking all other PRs it would be nice to get some speed on this one. 
- A container with the `nullable` property not set will no longer always be considered changed when running `cdf deploy`.
No changes.

🎾fix: wrong default in dumping containers

---

cognite_toolkit/_cdf_tk/commands/pull.py
tests/test_unit/test_cli/test_behavior.py

This issue was caused by having two loaders (standardized interface to work with CDF resources) to work with Groups (one for all scoped and one of resource scoped). When pulling the group (retrieving the Group from CDF and writing it to the local configuration), the first loader would write correctly to the local file. While the second pass, would cause some of the capabilities disappear. Solution is to only use one of the loaders for groups.
Found a logic mistake in the if conditions for skipping unsupported loaders, so fixed that issue as well.
- Running `cdf modules pull` no longer skips capabilities for Group resources.
- Running `cdf modules pull` now correctly skips unsupported resources such as `HostedExtractor` `source` and `destination`, as well as Functions and Streamlit apps. …

[CDF-24080] 👨🏼‍🏭Pull group missing capabilities

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/classic_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/hosted_extractors.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/timeseries_loaders.py
tests/data/complete_org/config.dev.yaml
tests/data/complete_org/modules/my_example_module/data_models/instance.Space.yaml
tests/data/complete_org/modules/my_example_module/timeseries/my_subscription.DatapointSubscription.yaml
tests/data/complete_org/modules/my_example_module/transformations/first.transformation.yaml
tests/data/complete_org/modules/my_example_module/transformations/inline.Transformation.yaml
tests/data/complete_org/modules/my_example_module/workflows/first.Workflow.yaml
tests/data/complete_org/modules/my_example_module/workflows/first.WorkflowTrigger.yaml
tests/test_unit/test_cdf_tk/test_commands/test_build.py
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml

Even though these parameters are used, we get `UnusedParamterWarning`s
**Context**: The `UnusedParamterWarning` comes from comparing the resource specification to the configuration. We obtain the resource specification by looking at the write format of the resource data class. This PR fixes mistakes in the resource spec generation for HostedExtractor Source, datapoint subscriptoin, and event write classes. 
- When running `cdf build`, the Toolkit no longer gives `UnusedParameterWarning` for all Hosted Extractor Source parameters, the filter parameter in DatapointSubscription, and the assetExternalIds parameter for Event resources. 
No changes.

[CDF-24076] 🏌️No unused parameter warnings for hosted extractors sources.

---

cognite_toolkit/_cdf.py
cognite_toolkit/_cdf_tk/commands/build.py
cognite_toolkit/_cdf_tk/constants.py
cognite_toolkit/_cdf_tk/hints.py

- When running `cdf build` and missing a build variable you know get a URL to the relevant documentation.
No changes.

[CDF-24130] 🍽 Improved hint for missing variables

---

cdf.toml
cognite_toolkit/_cdf_tk/apps/_dump_app.py
cognite_toolkit/_cdf_tk/commands/dump_resource.py
cognite_toolkit/_cdf_tk/feature_flags.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/workflow_loaders.py
cognite_toolkit/_cdf_tk/utils/cdf.py
tests/test_integration/test_commands/test_deploy.py
tests/test_unit/test_cdf_tk/test_loaders/test_function_loader.py
tests/test_unit/test_cdf_tk/test_loaders/test_transformation_loader.py
tests/test_unit/test_cdf_tk/test_loaders/test_workflow_loaders.py
tests/test_unit/test_cdf_tk/test_utils/test_cdf.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_3d_valhall.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_asset_valhall.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_files_valhall.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_timeseries_valhall.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_entity_matching.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_example_pump_asset_hierarchy.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_infield_location.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_infield_second_location.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_ingestion.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_inrobot_common.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_oid_example_data.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml

Release `0.5.0`. This is done by removing the alpha flags for the 4 features that are planned for v5.
- The `cdf dump datamodel` no longer includes data models that are global (in system space). You can get the original behavior by using the `--include-global` flag.
- Toolkit now stores a hash of the credentials of Workflow/Transformation/Function in the resources such that the resource is updated when the credentials change.
- For Workflow/Transformations/Function Toolkit no longer falls back to Toolkit credentials when validation-type != 'dev' in the `config.[env].yaml`. 
- Toolkit now support for `cdf dump workflow/transformation/group/node`.
No changes.

Release 0.5.0

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/file_loader.py
tests/test_unit/test_cdf_tk/test_loaders/test_file_metadata_loader.py

User error:
- Updating a FileMetadata or Streamlit app without a dataSetId no longer raiser a `KeyError` when using the `cdf deploy` command.
No changes.

[CDF-24410] 🙃 Key error streamlit

---

cognite_toolkit/_cdf_tk/commands/dump_resource.py
tests/test_unit/approval_client/config.py
tests/test_unit/test_cli/test_behavior.py

The base class `CogniteResourceList` in the PySDK takes an iterable, but it exhausted the iterable in a checking, thus it practice it has to take a sequence.
- When running `cdf dump workflow` the Toolkit now includes triggers if the selected workflow has triggers.
No changes.

[CDF-24411] 	🐛 Fix skip workflow trigger

---

cognite_toolkit/_cdf_tk/cdf_toml.py

- Allow `--help` flag on `cdf.toml` and CLI version mismatch
No changes.

[CDF-24164] 🤓 fix: allow help on version mismatch

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/classic_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/timeseries_loaders.py
tests/test_unit/test_cdf_tk/test_loaders/test_classic_loaders.py
tests/test_unit/test_cdf_tk/test_loaders/test_time_series_loader.py

User error message:
In addition, to the two places the `....id(some_external_id, is_dry_run)` argument was missing, I have checked that everywhere else this is called is correctly passing the `is_dry_run` argument
- When deploying a TimeSeries or Sequence referencing an asset with the `--dry-run` flag, Toolkit no longer fails with `ResourceRetrievalError`.
No changes.

[CDF-23633] 🪲 Failed lookup not deployed asset

---

.github/workflows/build.yml

Guarantee that we support `3.11` and `3.13`.

[CDF-24460] 😅 CI run tests on 3.11 and 3.13

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/workflow_loaders.py
poetry.lock
pyproject.toml
tests/test_integration/test_loaders/test_resource_loaders.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_data_pipeline_files_valhall.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_entity_matching.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_ingestion.yaml

367 lines is the `poetry.lock` . This is  a ~+30-40 line change.
Terminal output
This found a bug in the PySDK: https://github.com/cognitedata/cognite-sdk-python/pull/2140, which needs to be merged first.
- Toolkit no longer redeployes WorkflowVersion if default values are not set for tasks.
No changes.

[CDF-24400] 🫤 Unchanged workflow redeployed.

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/data_organization_loaders.py
tests/test_integration/test_loaders/test_resource_loaders.py

Note there is also a soft delete issue for labels, but suggest we do not address it.
- When running `cdf deploy` on label resources, changes are no longer incorrectly reported as update, but instead delete + create.
No changes.

[CDF-24340] 😵‍💫 Report label update correctly

---

cognite_toolkit/_cdf_tk/client/data_classes/apm_config_v1.py
tests/test_unit/test_cdf_tk/test_client/test_apm_config_v1.py

Today Toolkit implicitly supports Infield configurations through supporting Nodes. This is causing complexity on the user side as the Infield configuration contains for example `dataSetId` which the user is then responsible for looking up across CDF projects. This PR adds explicit support for the Infield Configuration. 
This PR adds the data class for the APM Config node.

[CDF-24461] 🙃  Support Infield Configuration Part 1

---

cognite_toolkit/_cdf_tk/commands/dump_resource.py
tests/test_integration/test_commands/test_dump_data_model.py

See changelog below.
- The command `cdf dump datamodel` no longer skips views, containers, and spaces, when you select a global model. For example, `cdf dump datamodel cdf_cdm CogniteCore v1`, now dumps all views, containers and spaces.
No changes.

[CDF-24416] 🔩 Dump global data model no longer skips views, containers, and spaces

---

cdf.toml
cognite_toolkit/_cdf_tk/client/data_classes/apm_config_v1.py
cognite_toolkit/_cdf_tk/feature_flags.py
cognite_toolkit/_cdf_tk/loaders/__init__.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/__init__.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/fieldops_loaders.py
tests/data/complete_org_alpha_flags/modules/my_example_module/cdf_applications/my_location.InfieldV1.yaml
tests/test_unit/test_cdf_tk/test_client/test_apm_config_v1.py
tests/test_unit/test_cdf_tk/test_loaders/test_base_loaders.py
tests/test_unit/test_cdf_tk/test_loaders/test_fieldops_loaders.py
tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org_alpha_flags.yaml
tests/test_unit/utils.py

Part 2 of #1531. 
Today Toolkit implicitly supports Infield configurations through supporting Nodes. This is causing complexity on the user side as the Infield configuration contains for example dataSetId which the user is then responsible for looking up across CDF projects. This PR adds explicit support for the Infield Configuration.
This PR uses the data class from the last PR and creates an Infield Loader.
- (alpha) Support for Infield resource.
No changes.

[CDF-24461] 🧁 Support Infield Configuration Part 2

---

cognite_toolkit/_builtin_modules/models/cdf_scene/data_models/containers/scene_Cdf3dRevisionProperties.Container.yaml
cognite_toolkit/_builtin_modules/models/cdf_scene/data_models/containers/scene_Image360CollectionProperties.Container.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_scene.yaml

Users of the built-in 3d configuration module got in trouble because two containers lacked `usedFor` and defaulted to `node`, where in reality they are meant for edges.
- Added missing usedFor: edge variables in 3d containers 
No changes.

[CDF-24483] Added 'usedFor' variable to make sure 3d data model is correct

---

cognite_toolkit/_cdf_tk/commands/repo.py

I was surprised to see no `.github/workflows/deploy.yaml` file after calling `cdf-tk repo init --host=Github`. The file is only created when the option matches "GitHub" with a capital H.
- Currently the `--host=` option value is ignored if it does not case-sensitively match a value in the `REPOSITORY_HOSTING` array. This change makes the matching case-insensitive and falls back to the "Other" repository hosting option if no match is found.
No changes.

repo: accommodate different letter casings in --host= option

---

.gitignore

The fix in #1546 introduced a fix to the virtual environment. This means all folders starting with `function_local_venvs` must ignored.

😐 Fix git ignore

---

cognite_toolkit/_cdf_tk/resource_classes/threedmodels.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_threedmodels.py

This PR introduces pydantic model for 3D Model Resource class that matches the YAML file format that toolkit expects.

[CDF-24575] Pydantic Validation for 3D models

---

cognite_toolkit/_cdf_tk/resource_classes/labels.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_labels.py

This PR introduces pydantic model for Label Resource class that matches the YAML file format that toolkit expects.

[CDF-24577] Pydantic Validation for Labels

---

cognite_toolkit/_builtin_modules/contextualization/cdf_p_and_id_parser/functions/contextualization_p_and_id_annotater/handler.py
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_p_and_id_parser.yaml

No changes.
- The module `cdf_p_and_id_parser` had a bug in the example function, were it did not filter correctly on the instance ID set in the configuration This is now fixed.

[CDF-24651] 👷 Fix template

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py
cognite_toolkit/_cdf_tk/resource_classes/__init__.py
cognite_toolkit/_cdf_tk/resource_classes/capabilities.py
cognite_toolkit/_cdf_tk/resource_classes/groups.py
cognite_toolkit/_cdf_tk/validation.py
tests/test_unit/test_cdf_tk/test_commands/test_build.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_capabilities.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_groups.py
tests/test_unit/test_cdf_tk/test_validation/test_validate_resource_pydantic.py

Toolkit: CLI for managing CDF configuration as code. The CDF resources are configured in YAML files that are typically checked into version control. 
Context: Up until now we have used the `cognite-sdk` data classes when loading these YAML files. This gives poor error messages when there are errors in the YAML files. In addition, Toolkit has a few deviation from the API spec, the most common Toolkit always uses external IDs instead of internal IDs. We have made the decision to implement `pydantic` to be able to give better error messages to the user when they mistype their `YAML` files.
Reason for size of this PR: Our Groups API has a lot of capabilities.
- Improved error message if group is not following the API specifications. 
No changes.

[CDF-23856] 🚶 Pydantic Group

---

cognite_toolkit/_cdf_tk/apps/_core_app.py

There have been multiple cases where the default behaviour of load_dotenv() has confused users and caused problems because ordinary environment variables take precedence over the .env file, for example `CDF_PROJECT`:
What the user expects the Toolkit to use: 
```.env
CDF_PROJECT=my_dev_project 
CDF_CLUSTER=westeurope-1
...
```
What the Toolkit uses (default load_dotenv())
```
echo $CDF_PROJECT
my_prod_project  
```
The `override_env` flag is designed to avoid that, but most users are unaware of it. We think it is unlikely that users want to mix and match.
- If the user uses a .env file, it takes precedence over local environment variables
No changes.

Making .env override default True

---

cdf.toml
cognite_toolkit/_cdf_tk/apps/_dump_app.py
cognite_toolkit/_cdf_tk/feature_flags.py
tests/test_integration/test_commands/test_dump_data_model.py

Dumping assets and timeseries goes to csv/parquet format, while data models, nodes, groups, transformations, and workflows goes to YAML thus configuration format. Suggest we split these before the introduction of dump events/files/location filters to make it clear what you are dumping to disk.
- [alpha] Introduces new `alpha` flag `dump-data` that splits the `cdf dump` plugin command into `cdf dump data` and `cdf dump config`. This is to make it clearer what is data and what is configurations.
No changes.

[prep CDF-24554]  Prep dump events

---

cognite_toolkit/_cdf_tk/resource_classes/__init__.py
cognite_toolkit/_cdf_tk/resource_classes/securitycategories.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_securitycategories.py

We have added several `pydantic` classes which will be used for validation. To avoid merge conflicts these have not yet been included in the `__init__` file of the module. This PR does that work for the latest pydantic classes that @Aashutosh-cognite has added.

Expose new yaml classe in module

---

.vscode/launch.json
cognite_toolkit/_cdf_tk/client/api/location_filters.py
cognite_toolkit/_cdf_tk/client/api/lookup.py

Letting the Location Filter API do the flattening 
- Set the LocationFilter API flag flat=True, making the recursive lookup in the code redundant
No changes.

Flattened location filter list on API call

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
cognite_toolkit/_cdf_tk/resource_classes/transformations.py
cognite_toolkit/_cdf_tk/validation.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_capabilities.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_transformations.py

Start using the newly created `TransformationYAML` for validation in the `cdf build` command.
- In the `cdf build` command improved feedback if transformations configurations is not following the specifications.
No changes.

Use pydantic for transformation validation

---

cognite_toolkit/_cdf_tk/client/_toolkit_client.py
cognite_toolkit/_cdf_tk/client/api/extended_timeseries.py
cognite_toolkit/_cdf_tk/client/data_classes/extended_timeseries.py
cognite_toolkit/_cdf_tk/client/data_classes/pending_instances_ids.py
tests/test_integration/conftest.py
tests/test_integration/test_toolkit_client/test_extended_timeseries.py

**REVIEWER**: The core part of this PR is ~90 lines, the `.set_instance_ids()` method in the `ExtendedTimeSeriesAPI`. The rest is copy-paste from the CogniteSDK with addding `pending_instance_ids` to the `ExtendedTimeSeries` and same for the `.retrieve`, `.retrieve_multiple` and `.list` methods with setting `alpha` flag and returning `ExtendedTimeSeries`.
In the upgrade from `TimeSeries` to `CogniteTimeSeries`, we need to link the newly created `CogniteTimeSeries` nodes to existing asset-centric timeseries to avoid reingesting all datapoints. This is the first PR in building this tooling that can do that linking. The tooling will depend on an alpha feature in the `timeseries` endpoint which accepts setting a property `pendingInstanceId` that is used as follows.
1. Set `pendindInstanceId` …

[CDF-24918] ⏱ Toolkit client set-pending-instance-id

---

cognite_toolkit/_cdf_tk/client/_toolkit_client.py
cognite_toolkit/_cdf_tk/client/api/extended_data_modeling.py
cognite_toolkit/_cdf_tk/client/api/statistics.py
cognite_toolkit/_cdf_tk/client/data_classes/statistics.py
cognite_toolkit/_cdf_tk/client/testing.py
tests/test_integration/test_toolkit_client/test_data_modeling_statistics.py

This adds the `statistics` endpoint to the internal `ToolkitClient`, i.e., not exposed to end-users.
This is a copy of this PR that has already been through risk-review: https://github.com/cognitedata/neat/pull/1163
**Context**: Toolkit will be used in migration of timeseries/files/canvas. All these requires writing nodes/edges to CDF in large amounts. We need the statistics endpoint (even though it is not yet even in alpha) to ensure that Toolkit cannot be used to fill up a CDF projects with nodes and edges, as that can cause data loss from applications such as Infield, Canvas, or other third-party applications. This has already happen in the past with Neat.

[CDF-24932] 📊 Added statistics API

---

cognite_toolkit/_cdf_tk/apps/_dump_app.py
cognite_toolkit/_cdf_tk/commands/dump_data.py
cognite_toolkit/_cdf_tk/utils/interactive_select.py
tests/test_unit/test_cdf_tk/test_commands/test_dump_data.py
tests/test_unit/test_cdf_tk/test_utils/test_interactive_select.py

Adds support for dumping file metadata to csv/parquet.
- [alpha] Support for dumping files medata, `cdf dump data filesmetadata`. To enable this set the flag `dump_data = true`.
No changes.

[CDF-24555] 📂 Support dump files

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
tests/test_integration/test_loaders/test_resource_loaders.py

See changelog below
- When running `cdf deploy`, Toolkit no longer overwrites nodes that are existing. Instead they are updated. This means if there is a property that is not in the local configuration but is set in CDF, Toolkit will not overwrite. 
No changes.

[CDF-24953] Fix node update

---

LIBRARIES.md

Added a guide for authors/maintainers of external template libraries, an alpha feature added in #1607 
- [alpha] Authoring guide **LIBRARIES.md** 
No changes.

[CDF-24993] Guide for writing external package libraries

---

.gitignore
cognite_toolkit/_cdf_tk/commands/_migrate/__init__.py
cognite_toolkit/_cdf_tk/commands/_migrate/data_classes.py
cognite_toolkit/_cdf_tk/commands/_migrate/timeseries.py
tests/test_unit/test_cdf_tk/test_commands/test_timeseries_migration.py
tests/test_unit/test_cdf_tk/test_utils/test_collection.py

This is a pure refactoring. 
1. First making the `_migrate.py` module into a package. Motivation is to separate out the data classes from the command.
2. Move the reading csv logic out from the `MigrateTimeseriesCommand` to the `MigrationMappingList` class. This will make it easier to reuse across multiple migration commands.

[prep CDF-24984] 👷 Refactor migration command

---

cognite_toolkit/_cdf_tk/commands/_profile.py

<del>Stacked on #1614</del>
- [alpha] The `cdf profile asset-centric` now shows the number of transformations that writes to each resource type.
No changes.

[CDF-24920]➡Transformation targets

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/classic_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/data_organization_loaders.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/file_loader.py
cognite_toolkit/_cdf_tk/validation.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_asset.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_dataset.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_event.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_filemetadata.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_labels.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_transformations.py

The YAML classes we use for validation are already made. This PR connects them to the loader class such that they will be used in the `cdf build` command. In addition, I made a set of tests cases for each as well as updated the function that humanize the pydantic errors. 
- In the `cdf build` command, Toolkit now gives improved warning messages if the syntax in the configuration file is incorrect for `assets`, `events`, `filemetadata`, `dataset`, and `labels`.
No changes.

⛓Use YAML classes in the validation of assets, events, filemetadata, dataset, and labels

---

cognite_toolkit/_cdf_tk/client/data_classes/agents.py

When Agents are created through the Agent CRUD API [alpha], they need to have the (undocumented) property `labels: ['published']`. This PR adds the ability to add labels to the resource. 
- [alpha] Agent resource now has `labels` property
No changes.

[CDF-24957] Support for 'labels' in Agent resource

---

cognite_toolkit/_cdf_tk/commands/clean.py
cognite_toolkit/_cdf_tk/commands/deploy.py
tests/test_unit/test_cdf_tk/test_loaders/test_base_loaders.py

**Context** I want to reuse the logic from the deploy command in the upcoming `cdf migrate prepare` command to deploy a migration model. This is currently not possible as the deploy command expects resources to be in a file and not already in memory. This PR is part 1 of refactoring of the deploy command, such that it becomes easier to read and reuse. 
The refactoring I have done in this PR is to split the `.execute()` method into smaller function for increased readability. 
The current version is 106 lines long, while the new one introduce in this PR is 14. 
Note there is zero change to logic, thus not touching any tests.

[prep CDF-24984] 👷Refactor deploy command Part 1

---

cognite_toolkit/_cdf_tk/commands/pull.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
tests/test_unit/test_cli/test_behavior.py

<del>Stacked on #1637</del>
Implementation of fix for pulling transformations and workflow triggers.
- The `cdf modules pull` command now only requires resources to be defined with their identifiers. For example, you can now define a transformation configuration with only `externalId` and then pull the rest of the definition from CDF.
No changes.

[CDF-24874, CDF-24773] 🐞 Pull workflow trigger/transformation

---

cognite_toolkit/_cdf_tk/apps/_core_app.py
cognite_toolkit/_cdf_tk/commands/clean.py
cognite_toolkit/_cdf_tk/commands/deploy.py
cognite_toolkit/_cdf_tk/data_classes/_deploy_results.py
cognite_toolkit/_cdf_tk/loaders/_worker.py
cognite_toolkit/demo/_base.py
module_upgrade/run_check.py
tests/test_integration/test_commands/test_deploy.py
tests/test_integration/test_loaders/test_resource_loaders.py
tests/test_unit/test_cdf_tk/test_commands/test_deploy.py
tests/test_unit/test_cdf_tk/test_loaders/test_base_loaders.py
tests/test_unit/test_cdf_tk/test_loaders/test_container_loader.py
tests/test_unit/test_cdf_tk/test_loaders/test_data_model_loader.py
tests/test_unit/test_cdf_tk/test_loaders/test_data_set_loader.py
tests/test_unit/test_cdf_tk/test_loaders/test_extraction_pipeline_loader.py
tests/test_unit/test_cdf_tk/test_loaders/test_function_loader.py
tests/test_unit/test_cdf_tk/test_loaders/test_group_loader.py
tests/test_unit/test_cdf_tk/test_loaders/test_view_loader.py
tests/test_unit/test_cdf_tk/test_loaders/test_worker.py
tests/test_unit/test_cli/test_behavior.py
tests/test_unit/test_cli/test_command_sequences.py

<del>Stacked on #1644 </del>
**Context** I want to reuse the logic from the deploy command in the upcoming `cdf migrate prepare` command to deploy a migration model. This is currently not possible as the deploy command expects resources to be in a file and not already in memory. This PR is part 1 of refactoring of the deploy command, such that it becomes easier to read and reuse. 
In this PR I have:
1. Split the now renamed method `prepare_resources` into three smaller methods in the `Resource Worker`. 
2. Split the now named `deploy_resource_type` method into smaller methods. This is increased readability and ease of reuse.
3. Renaming of all the deploy methods in the DeployCommand to reflect the abstraction level.
Note there is zero change to logic, thus not touching any tests.

[prep CDF-24984] 👷Refactor deploy command part2

---

cognite_toolkit/_cdf_tk/client/data_classes/canvas.py
tests/test_unit/test_cdf_tk/test_client/test_canvas.py

These classes are generated with `pygen`. The generated classes are split into two PRs to stay below the 500 limit.
Motivation for adding them support migration of Canvas from asset-centric to data modeling.

[prep CDF-24745] 🤵Canvas data classes part 1

---

tests/test_integration/test_commands/test_migrate_timeseries.py

The `test_migrate_timeseries_command` fails to run in parallel as it creates and deletes the same timeseries. This ensures that the timeseries used for testing migrations are unique for each run.

💣Fix fragile tests

---

cognite_toolkit/_cdf_tk/client/api/extended_timeseries.py
tests/auth_utils.py
tests/test_integration/test_toolkit_client/test_extended_timeseries.py
tests/test_unit/test_cdf_tk/test_client/conftest.py
tests/test_unit/test_cdf_tk/test_client/test_extended_timeseries.py
tests/test_unit/test_cdf_tk/test_client/test_instances.py

This implements the unlink endpoint for timeseries. Currently, this is only deployed in a dev cluster. The unlink endpoint enables you to unlink CogniteTimeSeries from an asset centric timeseries. This is useful in the case when you want to delete the CogniteTimeSeries nodes, but not lose the datapoints stored. 
The expected way this will be used
1. Unlink asset-centric timeseries from CogniteTimeSeries.
2. Delete CogniteTimeSeries.
3. Set pending instance ID on the asset-centric timeseries.
4. Create new CogniteTimeSeries.
This is necessary if you want the asset-centric timeseries to be linked to a different node than what is currently linked to.

[CDF-25070] ⛓️‍💥 Unlink timeseries

---

tests/test_integration/test_commands/test_migrate_prepare.py

I am changing the migration model we are using. This causes the integration test that deploys it to fail as it is now in different versions depending on which branch you run the test from. Temporarily disabling it.
Ref: https://github.com/cognitedata/toolkit/pull/1706

Temporarily skip test

---

cognite_toolkit/_cdf_tk/constants.py
tests/test_unit/test_cdf_tk/tests_constants.py

We have a tests that picks up broken links, but that test was broken so it did not run or report back. Fixed it.
- Warnings that contains the URL to to auth and config docs no longer gives 404.
No changes.

[CDF-25165] ⛓Fix 404 links

---

cognite_toolkit/_cdf_tk/apps/_dump_app.py
cognite_toolkit/_cdf_tk/utils/aggregators.py
cognite_toolkit/_cdf_tk/utils/interactive_select.py
tests/test_unit/test_cdf_tk/test_utils/test_interactive_select.py

* Reuse the aggregators in the interactive select implementations. 
* Introduce `operation` parameter so that the interactive select can be used for other operations than `dump`.

[CDF-25033] 🏗 Refactor interactive select

---

cognite_toolkit/_cdf_tk/client/data_classes/capabilities.py
tests/test_unit/test_cdf_tk/test_client/test_capabilities.py

**Context**: Toolkit has functionality such as profiling and auth that depends on the access level of the user. This PR prepares for a `get_scope()` method that returns the scope given an action. 
For example, in `cdf profile assets` we can input `get_scope(AssetsAcl.Action.Read)` and know whether the user has access to all assets, specific datasets or nothing.

[prep CDF-25149] 🔨 Introduce scope logic

---

cognite_toolkit/_cdf_tk/builders/_location.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py
tests/test_unit/test_cdf_tk/test_loaders/test_locations_loader.py
tests/test_unit/test_cli/test_behavior.py

Adds topological sort of location filters before creations to ensure that parents are created before children.
- When running `cdf deploy`, Toolkit now accounts for the dependencies between location filters in different modules.
No changes.

[CDF-25064] 🦗 Fix location filter deploy order

---

cognite_toolkit/_cdf_tk/client/_toolkit_client.py
cognite_toolkit/_cdf_tk/client/api/extended_files.py
cognite_toolkit/_cdf_tk/client/data_classes/extended_filemetadata.py
cognite_toolkit/_cdf_tk/client/data_classes/extended_filemetdata.py
tests/test_integration/test_toolkit_client/conftest.py
tests/test_integration/test_toolkit_client/test_extended_files.py
tests/test_integration/test_toolkit_client/test_extended_timeseries.py
tests/test_unit/test_cdf_tk/test_client/test_extended_filemetadata.py

**Context**: This is part of the `alpha` migration tooling in Toolkit, for overview [see here](https://cognitedata.atlassian.net/wiki/spaces/~170890702/pages/5455773697/Migration+Tooling+in+Toolkit). This is step 3 of that process, enabling linking of asset-centric files to cognite-files, such that the new CogniteFile can point to an existing asset-centric file and thus not needing to download and reupload the file content.
In this PR, I introduce `.set_pending_ids` for files which is set on asset-centric files in preparation for the creation of a CogniteFile. **Reviewer**: This follows the same pattern that we are doing for timeseries.

[prep CDF-25018] 📋 Support set-pending-ids for files

---

cognite_toolkit/_cdf_tk/client/api/migration.py
cognite_toolkit/_cdf_tk/client/data_classes/migration.py
cognite_toolkit/_cdf_tk/client/testing.py
tests/test_integration/test_toolkit_client/test_migration.py

Context: This is part of the alpha migration tooling in Toolkit, for overview [see here](https://cognitedata.atlassian.net/wiki/spaces/~170890702/pages/5455773697/Migration+Tooling+in+Toolkit). This is step 4 of that process, enabling downloading the instance source of migrated resources. This will, for example, be used by the Canvas migration to lookup the instance Id of asset-centric resources in a Chart.
Note the `InstanceSource` classes are generated by `pygen`.

[CDF-25194] 👷‍♂️ Update instance source API

---

cognite_toolkit/_cdf_tk/client/_toolkit_client.py
cognite_toolkit/_cdf_tk/client/api/lookup.py
cognite_toolkit/_cdf_tk/client/api/search.py
cognite_toolkit/_cdf_tk/client/data_classes/search_config.py
cognite_toolkit/_cdf_tk/client/testing.py
cognite_toolkit/_cdf_tk/commands/dump_resource.py
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py
tests/test_integration/test_toolkit_client/test_locations.py
tests/test_integration/test_toolkit_client/test_search_config.py
tests/test_unit/approval_client/config.py
tests/test_unit/test_cdf_tk/test_commands/test_dump_resource.py

Small preparation for adding SearchConfiguration support into Toolkit.
Refactoring:
* Added docstring to SearchConfigurationWrite. Even though this is not used outside Toolkit developers, it is still helpful to have the docstring.
* Moved `search_configurations` and `location_filters` under `search`. So instead of `client.search_configurations.list()` and `client.location_filters.list()` it is now `client.search.configurations.list()` and `client.search.locations.list()`.

[prep CDF-25251] 🧑‍🎓Standardize Search client API

---

cognite_toolkit/_cdf_tk/utils/cdf.py
tests/test_integration/test_utils/test_cdf.py
tests/test_unit/test_cdf_tk/test_commands/test_dump_data.py

This is preparation for supporting `cdf profile assent-centric --hierarchy my_hierarchy`, i.e., enable the user to list meatdata and labels in addition to counts used for a single hierarchy.
This PR extends the `label_count` to support filtering on hierarchy and data sets.

[prep CDF-25249] 💦 Support filtering for label listing

---

cognite_toolkit/_cdf_tk/commands/_profile.py
tests/test_unit/test_cdf_tk/test_commands/test_profile.py

On `cdf profile assets`
- [alpha] The `cdf profile` commands now skips repeated values in the table terminal output. This is to increase the readability.
No changes.

[CDF-25193] 🧑‍🎨 cdf profile nicer terminal output

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/workflow_loaders.py

**Context**; Cognite Toolkit has standardized classes for all CDF resources for all CRUD operations called loaders. This PR updates the loader for WorkflowTrigger resources.
We added support for the CRUD operations for WorkflowTrigger resources in Toolkit before there was an upsert endpoint. As a workaround, we used list + delete + create. This PR takes advantage of the new upsert endpoint instead of the workaround. 
- When deploying a workflow trigger, Toolkit no longer deletes and recreates it. Instead, the trigger is updated.
No changes.

[CDF-25385] 😁 Use upsert instead of delete - create 

---

cognite_toolkit/_cdf_tk/utils/producer_worker.py
tests/test_unit/test_cdf_tk/test_utils/test_producer_worker.py

We use the `WorkerProducerExecutor` to download large amounts of data. This PR introduces a kill-switch to enable the user to abort this operation. 
- [alpha] In the `cdf dump data` methods, the user can now stop the downloading of data.
No changes.

[CDF-25357] ☠ Add kill switch

---

cognite_toolkit/_builtin_modules/common/cdf_auth_readwrite_all/auth/admin.readonly.group.yaml
cognite_toolkit/_builtin_modules/common/cdf_auth_readwrite_all/auth/admin.readwrite.group.yaml
cognite_toolkit/_cdf_tk/loaders/_resource_loaders/agent_loaders.py
pyproject.toml
tests/data/complete_org_alpha_flags/modules/my_example_module/agents/my.Agent.yaml
tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_auth_readwrite_all.yaml
uv.lock

Currently there are unofficial properties in the Agents API. These will likely be removed/changed, however, we cannot ignore them in a CICD setting as the unofficial property `labels` is used to determine whether an Agent is shown in the UI or not. 
This PR ensures that all unofficial properties are passed from the API to the YAML file in `cdf dump agents` and when reading the YAML file and deploying it with the `cdf deploy`. 
In addition, since we are updating the `cognite-sdk` to the version that includes the `AgentsAcl` we have to include this in the builtin modules read and read-write all. (We have a tests that ensure that these modules are up-to-date with all available ACLs.
- [alpha] Running `cdf dump agents` and `cdf deploy` with agents. Unofficial properties from the API are now …

[CDF-25387] 🤖 Publish agents issue

---

cognite_toolkit/_cdf_tk/utils/graphql_parser.py
tests/test_unit/test_cdf_tk/test_utils/test_graphql_parser.py

The GraphQL parser fails for directives that looks like this
```graphql
view(
rawFilter: {
hasData: [
{
type: "container"
space: "onse_logfile"
externalId: "LogFile"
}
]
}   version: "1"
)
```
due to the `version: "1"` is expected to be on a new line.
- [alpha] When deploying a GraphQL model, the Cognite Toolkit no longer fails for `.graphql` schema that uses directives with multiple components without line separation. 
No changes.

[CDF-25393] 😅 GraphQL parser error

---

cognite_toolkit/_cdf_tk/apps/_dump_app.py
cognite_toolkit/_cdf_tk/commands/dump_resource.py
tests/test_unit/test_cdf_tk/test_commands/test_dump_resource.py

Fixes the `cdf dump group` command such that the user can select multiple groups and not just one at a time. **Note** This command did not have any tests so I introduced tests for it. 
- When running command `cdf dump group` you can now select multiple groups.
No changes.

[CDF-25405] Fix support dumping multiple groups

---

cognite_toolkit/_cdf_tk/commands/modules.py
tests/test_unit/test_cdf_tk/test_commands/test_modules.py

Fixed a bug that caused loading of external libraries to fail due to wrong directory name
- Fixed a bug that caused loading of external libraries to fail due to wrong directory name
No changes.

External library loading bugfix 

---

tests/test_integration/test_toolkit_client/test_extended_files.py

When running the tests suite concurently, this frequently fail as they run against the same CDF project. This fixes the issue

🦑Tests concurrency issue

---

.github/workflows/release.yaml

We need to run coverage on merge to main to upload a report such that codecov can compare

🐛Upload coverage report

---

cognite_toolkit/_cdf_tk/loaders/_resource_loaders/agent_loaders.py
tests/test_integration/test_toolkit_client/test_extended_files.py

The file syncer frequently takes more than 10 seconds, increasing to 30.

🐛 Fix: flaky test

---

cognite_toolkit/_cdf_tk/resource_classes/datapoint_subscription.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_datapoint_subscription_yaml.py

We are in the progress of adding pydantic classes to match the YAML format Toolkit expects for configurations. The goal is to give better error message to the user on syntax errors.
This PR introduces the DatapointSubscription class to validate datapoint subsccriptions. Note this is not yet exposed, so no change to the end user.

[CDF-24818] 🍨 Datapoint subscription YAML class

---

cognite_toolkit/_cdf_tk/commands/_migrate/data_mapper.py

**Context**: This is part of the `alpha` migration tooling in Toolkit, for overview [see here](https://cognitedata.atlassian.net/wiki/spaces/~170890702/pages/5455773697/Migration+Tooling+in+Toolkit). This is step 3 and 4 of that process. 
This introduces a generalized interface that we will use to go from asset-centric assets/event/timeseries/files/annotations -> to DM equivalent. It will also be used for charts/canvas were the mapping operation is to update the asset-centric references to data modeling references.

[CDF-25666] 🗺 Data mapper interface

---

cognite_toolkit/_cdf_tk/resource_classes/extraction_pipeline.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_extraction_pipeline.py

We are in the progress of adding pydantic classes to match the YAML format Toolkit expects for configurations. The goal is to give better error message to the user on syntax errors.
This PR introduces the ExtractionPipelineYAML class to validate extraction pipeline. Note this is not yet exposed, so no change to the end user.

[CDF-24802] 🥟 Added ExtractionPipelineYAML

---

cognite_toolkit/_cdf_tk/apps/_migrate_app.py

You cannot give `externalId` for the asset-centric resources any more. Just internal ID

🐛Fix documentation

---

cognite_toolkit/_cdf_tk/client/data_classes/streamlit_.py

For streamlit apps the entrypoint is no longer required in the metadata (the information is stored in the file content json). In addition, if the hash of the code is not set, we now skip it instead of setting it to missing. This is when we dump the application using the new `cdf dump streamlit`. 
- When deploying streamlit apps that has been dumped with Toolkit, then entrypoint for the app is now correctly set.
No changes.

[CDF-25685] 🤗 Streamlit app entrypoint no longer required in metadata

---

cognite_toolkit/_cdf_tk/utils/validate_access.py
tests/test_unit/test_cdf_tk/test_utils/test_validate_access.py

This adds a check for whether the user can access assets. We will use this before migrating/downloading/uploading asset to verify that the user has access to do the operation, and if not, they get an appropriate error message.

[prep CDF-25015] 🕵  Added validation for asset access

---

cognite_toolkit/_cdf_tk/resource_classes/hosted_extractor_mapping.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_hosted_extractor_mapping.py

We are in the progress of adding pydantic classes to match the YAML format Toolkit expects for configurations. The goal is to give better error message to the user on syntax errors.
This PR introduces the HostedExtractorMappingYAMLclass to validate hosted extractor mappings. Note this is not yet exposed, so no change to the end user.

[CDF-24807] 🎍 Hosted Extractor Mapping YAML

---

cognite_toolkit/_cdf_tk/resource_classes/streamlit_.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_streamlit.py

We are in the progress of adding pydantic classes to match the YAML
format Toolkit expects for configurations. The goal is to give better
error message to the user on syntax errors.
This PR introduces the StreamlitYAML class to validate streamlit applications. Note this is not yet exposed, so no change
to the end user.

[CDF-24817] 🎏 StreamlitYAML

---

cognite_toolkit/_cdf_tk/utils/http_client/_client.py
cognite_toolkit/_cdf_tk/utils/http_client/_data_classes.py
tests/test_unit/test_cdf_tk/test_utils/test_http_client.py

In the HTTPCLient in Toolkit, we need to be able to do calls against the alpha version of the CDF API.  I will need to use this  in the migration, were I need it to set-pending-instance-ids on files and timeseries for example.

[CDF-25742] α Support setting alpha flag

---

cognite_toolkit/_cdf_tk/commands/_purge.py

We had a user purging the space instead of instances, leading to data loss. This is a stop-gap solution to try to avoid this happening again. Once #1977 and #1978 are merged, I will add a better solution for it in the reimplementation of this command.
- When running the `cdf purge space` command, the user will now get an extra warning.
No changes.

🚨Warning message on purge

---

cognite_toolkit/_cdf_tk/resource_classes/extraction_pipeline.py
tests/test_unit/test_cdf_tk/test_resource_classes/test_extraction_pipeline.py

Small bug in the YAML spec for extraction pipelines
- When running `cdf build` Toolkit no longer give warnings on extraction pipelines for unused field sendNotification. For example: ` In contacts[1] unused field: 'sendNotification'`
No changes.

🐛 API spec for extraction pipeline

---

cognite_toolkit/_cdf_tk/apps/_migrate_app.py
cognite_toolkit/_cdf_tk/commands/_download.py
cognite_toolkit/_cdf_tk/commands/_migrate/adapter.py
cognite_toolkit/_cdf_tk/commands/_upload.py
cognite_toolkit/_cdf_tk/storageio/__init__.py
cognite_toolkit/_cdf_tk/storageio/_applications.py
cognite_toolkit/_cdf_tk/storageio/_asset_centric.py
cognite_toolkit/_cdf_tk/storageio/_base.py
cognite_toolkit/_cdf_tk/storageio/_instances.py
cognite_toolkit/_cdf_tk/storageio/_raw.py
tests/test_integration/test_commands/test_migrate_assets.py
tests/test_integration/test_commands/test_migrate_files.py
tests/test_unit/test_cdf_tk/test_commands/test_migration_cmd/test_adapter.py
tests/test_unit/test_cdf_tk/test_commands/test_migration_cmd/test_command.py
tests/test_unit/test_cdf_tk/test_storageio/test_applications.py

This is a small quality-of-life improvemnt to the StorageIO (used to download/upload/migrate data)
* Moved out the `ConfigurableStorageIO` from `StorageIO` as multiple of the implementations did not support these methods.
* Removed unused part of `AssetCentricMigrationIOAdapter`.
* Switched the id type of `AssetCentricMigrationIOAdapter`  from int to `AssetCentricId`. This is preparation for having a `cdf migrate hierarchy` command that migrate assets, events, timeseries, and files in the same command. Then, we need the IDs to include the resource type.

[CDF-25880] 🍉Simplify StorageIO Adapter
